import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { ApiService } from './api.service';
import { IApiResponse } from '../models/api-response.model';

export interface IHubKpi {
  value: number;
  change: number;
}

export interface IHubModule {
  id: string;
  label: string;
  description: string;
  icon: string;
  route: string;
  active: boolean;
}

export interface IHubOverview {
  kpis: {
    conversationsAutomated: IHubKpi;
    humanEscalations: IHubKpi;
    revenueGenerated: IHubKpi;
    leadsCaptured: IHubKpi;
    aiAccuracy: IHubKpi;
  };
  modules: IHubModule[];
  recentActivity: {
    platform: string;
    type: string;
    isEscalated: boolean;
    wasAutoGenerated: boolean;
    updatedAt: string;
    authorName: string;
  }[];
  topByPlatform: { _id: string; count: number }[];
  channels: { platform: string; name: string }[];
}

@Injectable({ providedIn: 'root' })
export class AutomationHubService {
  constructor(private api: ApiService) {}

  getHubOverview(): Observable<IApiResponse<IHubOverview>> {
    return this.api.get('/automation/hub-overview');
  }
}
