export interface IInteraction {
  _id: string;
  organization: string;
  platform: Platform;
  type: InteractionType;
  platformId: string;
  platformUrl?: string;
  content: string;
  author: IAuthor;
  status: InteractionStatus;
  sentiment?: Sentiment;
  sentimentScore?: number;
  sentimentConfidence?: number;
  topics?: string[];
  intent?: string;
  urgency?: Urgency;
  aiSuggestion?: IAISuggestion;
  autoReplyEligible?: boolean;
  autoReplied?: boolean;
  assignedTo?: string;
  assignedBy?: string;
  assignedAt?: Date;
  assignmentReason?: string;
  assignmentHistory?: IAssignmentHistory[];
  intentBucket?: any;
  bucketAssignedBy?: 'keyword' | 'ai' | 'manual';
  labels?: ILabel[];
  priority?: Priority;
  tags?: string[];
  /** Star rating (1–5) for review-type interactions (e.g. Google Business) */
  rating?: number;
  metadata?: any;
  replies?: IReply[];
  responseCount?: number;
  internalNotes?: INote[];
  engagement?: IEngagement;
  platformCreatedAt: Date;
  respondedAt?: Date;
  resolvedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
  /** When false, conversation is treated as closed in inbox filters until reopened */
  chatOpen?: boolean;
  /** Linked unified contact ID (resolved from author identity) */
  contact?: string | null;
  /** Chat summary — written manually or generated by AI */
  summary?: string | null;
  /** Suggested next action from AI (only set on AI-generated summaries) */
  summarySuggestedAction?: string | null;
  summaryGeneratedAt?: Date;
  summaryGeneratedBy?: 'ai' | 'manual' | null;
  /** Support desk ticket number (sequential per org, starts at 101) */
  chatNumber?: number;
  /** Formatted ticket reference e.g. #REP-101 */
  chatRef?: string;
}

export enum Platform {
  INSTAGRAM = 'instagram',
  FACEBOOK = 'facebook',
  WHATSAPP = 'whatsapp',
  YOUTUBE = 'youtube',
  GOOGLE = 'google',
  LINKEDIN = 'linkedin',
  WEBSITE = 'website'
}

export enum InteractionType {
  COMMENT = 'comment',
  DM = 'dm',
  REVIEW = 'review',
  MENTION = 'mention'
}

export enum InteractionStatus {
  UNREAD = 'unread',
  READ = 'read',
  REPLIED = 'replied',
  ASSIGNED = 'assigned',
  RESOLVED = 'resolved',
  SPAM = 'spam',
  ARCHIVED = 'archived'
}

export enum Sentiment {
  POSITIVE = 'positive',
  NEGATIVE = 'negative',
  NEUTRAL = 'neutral'
}

export enum Priority {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  URGENT = 'urgent'
}

export enum Urgency {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  URGENT = 'urgent'
}

export interface IAuthor {
  platformId: string;
  name: string;
  username?: string;
  email?: string;
  profileUrl?: string;
  avatarUrl?: string;
  /** Alternative field some APIs use for profile image */
  profilePicture?: string;
  followerCount?: number;
  isVerified?: boolean;
}

export interface IAISuggestion {
  content: string;
  confidence: number;
  generatedAt: Date;
  wasUsed?: boolean;
  feedback?: 'accepted' | 'modified' | 'rejected';
}

// User info when populated from backend
export interface IReplyUser {
  _id: string;
  firstName?: string;
  lastName?: string;
  email?: string;
}

export interface IReply {
  _id: string;
  content: string;
  sentBy: string | IReplyUser;
  sentAt: Date;
  platformResponseId?: string;
  wasAutoGenerated?: boolean;
  /** AI confidence score (0–1). Only set on auto-generated replies. */
  confidence?: number | null;
  /** AI-detected message type (small_talk, closing, business, unclear). */
  messageType?: string | null;
  status?: 'sent' | 'failed' | 'deleted' | 'received' | 'pending';
  /** Attachment sent with this reply (image/video/file) */
  attachmentUrl?: string;
  attachmentType?: 'image' | 'video' | 'file' | 'audio';

  // Platform reply fields (for replies from other users on YouTube/Instagram/etc)
  isPlatformReply?: boolean; // True if this is a reply from the platform, false if from app
  platform?: string; // youtube, instagram, facebook, google
  platformId?: string; // Platform-specific ID
  author?: {
    platformId?: string;
    name?: string;
    username?: string;
    profileUrl?: string;
    avatarUrl?: string;
    isVerified?: boolean;
  };
  sentiment?: 'positive' | 'negative' | 'neutral';
  platformUrl?: string;
}

export interface INote {
  _id: string;
  note: string;
  addedBy: string;
  addedAt: Date;
  isPrivate: boolean;
}

export interface IEngagement {
  likes: number;
  shares: number;
  views: number;
  replyCount: number;
}

export interface ILabel {
  _id: string;
  name: string;
  color?: string;
  description?: string;
  icon?: string;
}

export type InboxViewMode = 'all' | 'priority' | 'assigned' | 'needs_response' | 'overdue' | 'archived' | 'buckets';

/** Single value or multi-select (OR) — serialized as comma-separated query params. */
export type InboxFilterMulti<T extends string> = T | T[] | undefined;

export interface IInboxFilters {
  platform?: InboxFilterMulti<Platform>;
  type?: InboxFilterMulti<InteractionType>;
  sentiment?: InboxFilterMulti<Sentiment>;
  status?: InboxFilterMulti<InteractionStatus>;
  assignedTo?: string;
  viewMode?: InboxViewMode;
  search?: string;
  label?: InboxFilterMulti<string>;
  intentBucket?: string;
  /** Filter by post (e.g. from Content page "Comments" – show only comments for this post) */
  postId?: string;
  /** Date range filters (ISO date strings YYYY-MM-DD) */
  dateFrom?: string;
  dateTo?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
  /** Client-only: mapped to `chatOpen=true|false` query for GET /inbox */
  chatSession?: 'open' | 'closed';
}

export interface IAssignmentHistory {
  assignedTo: any;
  assignedBy: any;
  assignedAt: Date;
  reason?: string;
}

export interface IInboxStats {
  total: number;
  unread: number;
  assigned: number;
  replied?: number;
  resolved?: number;
  responseRate?: number;
  positive: number;
  negative: number;
  neutral: number;
  avgResponseTimeMinutes?: number | null;
  overdueCount?: number;
}

