export interface IInteraction {
  _id: string;
  organization: string;
  platform: Platform;
  type: InteractionType;
  platformId: string;
  platformUrl?: string;
  content: string;
  author: IAuthor;
  status: InteractionStatus;
  sentiment?: Sentiment;
  sentimentScore?: number;
  sentimentConfidence?: number;
  topics?: string[];
  intent?: string;
  urgency?: Urgency;
  aiSuggestion?: IAISuggestion;
  autoReplyEligible?: boolean;
  autoReplied?: boolean;
  assignedTo?: string;
  assignedAt?: Date;
  labels?: ILabel[];
  priority?: Priority;
  tags?: string[];
  metadata?: any;
  replies?: IReply[];
  responseCount?: number;
  internalNotes?: INote[];
  engagement?: IEngagement;
  platformCreatedAt: Date;
  respondedAt?: Date;
  resolvedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export enum Platform {
  INSTAGRAM = 'instagram',
  FACEBOOK = 'facebook',
  WHATSAPP = 'whatsapp',
  YOUTUBE = 'youtube',
  GOOGLE = 'google',
  WEBSITE = 'website'
}

export enum InteractionType {
  COMMENT = 'comment',
  DM = 'dm',
  REVIEW = 'review',
  MENTION = 'mention'
}

export enum InteractionStatus {
  UNREAD = 'unread',
  READ = 'read',
  REPLIED = 'replied',
  ASSIGNED = 'assigned',
  RESOLVED = 'resolved',
  SPAM = 'spam',
  ARCHIVED = 'archived'
}

export enum Sentiment {
  POSITIVE = 'positive',
  NEGATIVE = 'negative',
  NEUTRAL = 'neutral'
}

export enum Priority {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  URGENT = 'urgent'
}

export enum Urgency {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  URGENT = 'urgent'
}

export interface IAuthor {
  platformId: string;
  name: string;
  username?: string;
  email?: string;
  profileUrl?: string;
  avatarUrl?: string;
  followerCount?: number;
  isVerified?: boolean;
}

export interface IAISuggestion {
  content: string;
  confidence: number;
  generatedAt: Date;
  wasUsed?: boolean;
  feedback?: 'accepted' | 'modified' | 'rejected';
}

export interface IReply {
  _id: string;
  content: string;
  sentBy: string;
  sentAt: Date;
  platformResponseId?: string;
  wasAutoGenerated?: boolean;
  status: 'sent' | 'failed' | 'deleted';
}

export interface INote {
  _id: string;
  note: string;
  addedBy: string;
  addedAt: Date;
  isPrivate: boolean;
}

export interface IEngagement {
  likes: number;
  shares: number;
  views: number;
  replyCount: number;
}

export interface ILabel {
  _id: string;
  name: string;
  color: string;
  description?: string;
  icon?: string;
}

export interface IInboxFilters {
  platform?: Platform;
  type?: InteractionType;
  sentiment?: Sentiment;
  status?: InteractionStatus;
  assignedTo?: string;
  search?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

export interface IInboxStats {
  total: number;
  unread: number;
  assigned: number;
  positive: number;
  negative: number;
  neutral: number;
}

