export interface IInteraction {
  _id: string;
  organization: string;
  platform: Platform;
  type: InteractionType;
  platformId: string;
  platformUrl?: string;
  content: string;
  author: IAuthor;
  status: InteractionStatus;
  sentiment?: Sentiment;
  sentimentScore?: number;
  sentimentConfidence?: number;
  topics?: string[];
  intent?: string;
  urgency?: Urgency;
  aiSuggestion?: IAISuggestion;
  autoReplyEligible?: boolean;
  autoReplied?: boolean;
  assignedTo?: string;
  assignedBy?: string;
  assignedAt?: Date;
  assignmentReason?: string;
  assignmentHistory?: IAssignmentHistory[];
  labels?: ILabel[];
  priority?: Priority;
  tags?: string[];
  /** Star rating (1–5) for review-type interactions (e.g. Google Business) */
  rating?: number;
  metadata?: any;
  replies?: IReply[];
  responseCount?: number;
  internalNotes?: INote[];
  engagement?: IEngagement;
  platformCreatedAt: Date;
  respondedAt?: Date;
  resolvedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export enum Platform {
  INSTAGRAM = 'instagram',
  FACEBOOK = 'facebook',
  WHATSAPP = 'whatsapp',
  YOUTUBE = 'youtube',
  GOOGLE = 'google',
  LINKEDIN = 'linkedin',
  WEBSITE = 'website'
}

export enum InteractionType {
  COMMENT = 'comment',
  DM = 'dm',
  REVIEW = 'review',
  MENTION = 'mention'
}

export enum InteractionStatus {
  UNREAD = 'unread',
  READ = 'read',
  REPLIED = 'replied',
  ASSIGNED = 'assigned',
  RESOLVED = 'resolved',
  SPAM = 'spam',
  ARCHIVED = 'archived'
}

export enum Sentiment {
  POSITIVE = 'positive',
  NEGATIVE = 'negative',
  NEUTRAL = 'neutral'
}

export enum Priority {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  URGENT = 'urgent'
}

export enum Urgency {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  URGENT = 'urgent'
}

export interface IAuthor {
  platformId: string;
  name: string;
  username?: string;
  email?: string;
  profileUrl?: string;
  avatarUrl?: string;
  /** Alternative field some APIs use for profile image */
  profilePicture?: string;
  followerCount?: number;
  isVerified?: boolean;
}

export interface IAISuggestion {
  content: string;
  confidence: number;
  generatedAt: Date;
  wasUsed?: boolean;
  feedback?: 'accepted' | 'modified' | 'rejected';
}

// User info when populated from backend
export interface IReplyUser {
  _id: string;
  firstName?: string;
  lastName?: string;
  email?: string;
}

export interface IReply {
  _id: string;
  content: string;
  sentBy: string | IReplyUser;
  sentAt: Date;
  platformResponseId?: string;
  wasAutoGenerated?: boolean;
  status?: 'sent' | 'failed' | 'deleted' | 'received' | 'pending';
  
  // Platform reply fields (for replies from other users on YouTube/Instagram/etc)
  isPlatformReply?: boolean; // True if this is a reply from the platform, false if from app
  platform?: string; // youtube, instagram, facebook, google
  platformId?: string; // Platform-specific ID
  author?: {
    platformId?: string;
    name?: string;
    username?: string;
    profileUrl?: string;
    avatarUrl?: string;
    isVerified?: boolean;
  };
  sentiment?: 'positive' | 'negative' | 'neutral';
  platformUrl?: string;
}

export interface INote {
  _id: string;
  note: string;
  addedBy: string;
  addedAt: Date;
  isPrivate: boolean;
}

export interface IEngagement {
  likes: number;
  shares: number;
  views: number;
  replyCount: number;
}

export interface ILabel {
  _id: string;
  name: string;
  color?: string;
  description?: string;
  icon?: string;
}

export type InboxViewMode = 'all' | 'priority' | 'assigned' | 'needs_response' | 'overdue' | 'archived';

export interface IInboxFilters {
  platform?: Platform;
  type?: InteractionType;
  sentiment?: Sentiment;
  status?: InteractionStatus;
  assignedTo?: string;
  viewMode?: InboxViewMode;
  search?: string;
  label?: string; // Label ID for filtering
  /** Filter by post (e.g. from Content page "Comments" – show only comments for this post) */
  postId?: string;
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

export interface IAssignmentHistory {
  assignedTo: any;
  assignedBy: any;
  assignedAt: Date;
  reason?: string;
}

export interface IInboxStats {
  total: number;
  unread: number;
  assigned: number;
  replied?: number;
  resolved?: number;
  responseRate?: number;
  positive: number;
  negative: number;
  neutral: number;
  avgResponseTimeMinutes?: number | null;
  overdueCount?: number;
}

