import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges, OnInit, OnDestroy, ViewChild, ElementRef, ChangeDetectorRef, NgZone, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators, FormsModule } from '@angular/forms';
import { INBOX_DETAIL_ANIMATIONS } from '../inbox.animations';
import { DomSanitizer, SafeUrl, SafeHtml } from '@angular/platform-browser';
import { IInteraction, InteractionStatus, IAssignmentHistory } from '../../../core/models/interaction.model';
import { InboxService, INBOX_THREAD_MESSAGE_PAGE_SIZE } from '../../../core/services/inbox.service';
import { ThemeService } from '../../../core/services/theme.service';
import { UserService, IAvailableAgent } from '../../../core/services/user.service';
import { AuthService } from '../../../core/services/auth.service';
import { NotificationDataService } from '../../../core/services/notification-data.service';
import { SweetAlertService } from '../../../core/services/sweet-alert.service';
import { Observable, of, Subscription, timer, interval } from 'rxjs';
import { map, take } from 'rxjs/operators';
import { InboxAvatarService } from '../../../core/services/inbox-avatar.service';
import { MediaLibraryService } from '../../../core/services/media-library.service';
import { INBOX_EMOJI_LIST } from '../../../core/constants/inbox-emoji-list';
import { AiChatBubbleIconComponent } from '../../../shared/components/ai-chat-bubble-icon/ai-chat-bubble-icon.component';
import { MediaSelectorModalComponent } from '../../../shared/components/media-selector-modal/media-selector-modal.component';
import { Media } from '../../../core/models/media.model';
import { Platform } from '../../../core/models/interaction.model';
import { normalizeTimestampMs } from '../../../core/utils/inbox-bucket-chat-timeline';
import { WhatsAppTemplateService } from '../../../core/services/whatsapp-template.service';
import { WhatsAppTemplate } from '../../../core/models/whatsapp-template.model';
import {
  listWhatsAppTemplateParamSlots,
  buildWhatsAppOutboundTemplateComponents,
  WaParamSlot
} from '../../../core/utils/whatsapp-template-send.helpers';
import {
  buildWhatsAppTemplatePreviewDisplay,
  WhatsAppTemplatePreviewDisplay
} from '../../../core/utils/whatsapp-template-preview.helpers';
import {
  downloadInboxAttachmentFile,
  inboxAttachmentFilenameFromUrl,
  inboxReplyPdfDisplayName
} from '../../../core/utils/inbox-attachment-display';
import { InboxLinkifiedTextComponent } from '../../../shared/components/inbox-linkified-text/inbox-linkified-text.component';
import { CatalogService } from '../../../core/services/catalog.service';
import { IProduct } from '../../../core/models/product.model';
import { NotificationService } from '../../../core/services/notification.service';

/** An in-flight or failed reply injected optimistically into the timeline */
interface IOptimisticReply {
  _optimistic: true;
  content: string;
  sentAt: Date;
  sentBy: any;
  status: 'pending' | 'failed';
  isPlatformReply: false;
  wasAutoGenerated: false;
  attachmentUrl?: string;
  attachmentType?: 'image' | 'video' | 'file' | 'audio';
  attachmentDisplayName?: string;
  /** Present when outbound send uses WhatsApp Cloud API templates (retry). */
  whatsappTemplatePayload?: {
    name: string;
    languageCode: string;
    components: { type: string; parameters: Record<string, unknown>[] }[];
    /** Sent with WhatsApp outbound payload — backend reads for inbox bubble only */
    inboxUiPreview?: WhatsAppTemplatePreviewDisplay;
  };
  whatsappTemplatePreview?: WhatsAppTemplatePreviewDisplay;
}

/**
 * Inbox Detail Component - Single Responsibility Principle
 * Displays full interaction details and reply form
 */
@Component({
  selector: 'app-inbox-detail',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, FormsModule, MediaSelectorModalComponent, AiChatBubbleIconComponent, InboxLinkifiedTextComponent],
  templateUrl: './inbox-detail.component.html',
  styleUrls: ['./inbox-detail.component.scss'],
  animations: INBOX_DETAIL_ANIMATIONS,
})
export class InboxDetailComponent implements OnChanges, OnInit, OnDestroy {
  @Input() interaction: IInteraction | null = null;
  @Output() interactionUpdate = new EventEmitter<void>();
  @ViewChild('replyTextarea') replyTextarea?: ElementRef<HTMLTextAreaElement>;

  replyForm: FormGroup;
  submittingReply = false;
  replySuccess = false;
  generatingSuggestion = false;
  aiSuggestion: { content: string; confidence: number; usedKnowledgeBase: boolean } | null = null;
  suggestionError: string | null = null;
  /** Tracks avatar load errors so we can show initial fallback */
  avatarFallback: Record<string, boolean> = {};
  /** WhatsApp Business corner badge image load errors */
  waPlatformBadgeError: Record<string, boolean> = {};
  /** Used for star rating display (1–5) */
  readonly ratingStars = [1, 2, 3, 4, 5];
  /** Optimistic replies shown before server confirms */
  optimisticReplies: IOptimisticReply[] = [];

  /** Cached timeline so *ngFor gets a stable reference (stops scroll jump when audio/timeupdate triggers CD) */
  conversationTimeline: Array<{ type: 'message' | 'reply' | 'assignment' | 'note'; data: any; timestamp: Date }> = [];
  visibleConversationTimeline: Array<{ type: 'message' | 'reply' | 'assignment' | 'note'; data: any; timestamp: Date }> = [];
  private readonly timelinePageSize = 20;
  private visibleTimelineCount = 20;
  loadingOlderMessages = false;
  private readonly messagePreviewLimit = 160;
  private readonly expandedMessageKeys = new Set<string>();
  /** Timeline order for chat thread. */
  timelineSortOrder: 'asc' | 'desc' = 'asc';

  /** Server-side message pagination state */
  hasOlderMessages = false;
  private oldestMessageTimestamp: number | null = null;
  loadingOlderFromServer = false;
  /**
   * Accumulated incoming messages across all loaded pages.
   * Reset when switching conversations; prepended when loading older pages.
   */
  private allIncomingMessages: any[] = [];

  /** Whether the thread is scrolled near the bottom (controls FAB visibility) */
  isScrolledToBottom = true;
  
  // Agent assignment
  availableAgents: IAvailableAgent[] = [];
  loadingAgents = false;
  assigningAgent = false;
  currentUser: any = null;
  
  // Resolution
  resolvingInteraction = false;

  /** Chat session open/closed (inbox workflow) */
  updatingChatOpen = false;

  /** Deleting Facebook comment (on platform + DB) */
  deletingComment = false;
  deletingReplyId: string | null = null;
  openReplyActionsForId: string | null = null;

  /** Three-dots actions menu open state */
  showActionsMenu = false;

  /** Emoji picker visibility */
  showEmojiPicker = false;
  /** Left reply toolbar (emoji, AI, attach, catalog) — collapsed by default */
  replyToolbarExpanded = false;

  /** Media selector modal for sending image/video in reply */
  showMediaModal = false;
  /** Distinguishes reply attachment vs WhatsApp template header image picker. */
  mediaSelectorContext: 'reply' | 'waTemplateImage' | null = null;
  waTemplateImageSlotKey: string | null = null;

  /** Pending attachment (image/video/audio) to send with next reply; user can add caption then click Send */
  pendingAttachment: { publicUrl: string; mediaType: 'image' | 'video' | 'audio' | 'file'; media?: Media } | null = null;

  /** WhatsApp — send approved Cloud API templates from inbox */
  waReplyMode: 'text' | 'template' = 'text';
  waApprovedTemplates: WhatsAppTemplate[] = [];
  waTemplatesLoading = false;
  waSelectedTemplate: WhatsAppTemplate | null = null;
  waTemplateSlots: WaParamSlot[] = [];
  waTemplateParamValues: Record<string, string> = {};

  /** In-chat voice recording */
  isRecording = false;
  isUploadingRecording = false;
  recordingDurationSec = 0;
  private mediaRecorder: MediaRecorder | null = null;
  private recordingStream: MediaStream | null = null;
  private recordedChunks: Blob[] = [];
  private recordingTickSub?: Subscription;

  /** Same picker as list inbox — single source: `INBOX_EMOJI_LIST` */
  readonly emojiList: readonly string[] = INBOX_EMOJI_LIST;

  // ── WhatsApp Product Picker ────────────────────────────────────────────────
  showProductPickerModal = false;
  pickerProducts: IProduct[] = [];
  loadingPickerProducts = false;
  selectedPickerProduct: IProduct | null = null;
  productPickerSearch = '';
  productPickerBodyText = '';
  sendingProduct = false;
  productPickerError = '';

  /** Products suggested by AI based on the current conversation */
  aiSuggestedProducts: IProduct[] = [];
  sendingAiSuggestedProduct: string | null = null;

  // Subscriptions
  private subscriptions: Subscription[] = [];
  /** One-shot delays (focus/scroll/success banner) — no raw setTimeout */
  private readonly timedTasks = new Subscription();

  ngOnInit(): void {
    this.currentUser = this.authService.currentUserValue;
    this.loadAvailableAgents();
  }

  /** Called by the container (or inline) after getInteraction resolves; captures pagination metadata. */
  applyPaginationMeta(pagination?: { hasOlderMessages: boolean; oldestMessageTimestamp: number | null }): void {
    if (!pagination) return;
    this.hasOlderMessages = pagination.hasOlderMessages;
    if (pagination.oldestMessageTimestamp != null) {
      this.oldestMessageTimestamp = pagination.oldestMessageTimestamp as number;
    } else {
      this.syncOldestMessageCursorFromLoadedIncoming();
    }
  }

  /** msgBefore must match BSON `timestamp` units; `allIncomingMessages` is chronological (oldest at [0]). */
  private syncOldestMessageCursorFromLoadedIncoming(): void {
    const row = this.allIncomingMessages[0];
    const ts = row?.timestamp;
    if (ts != null && typeof ts === 'number' && !Number.isNaN(ts)) {
      this.oldestMessageTimestamp = ts;
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['interaction']) {
      const prev: IInteraction | null = changes['interaction'].previousValue;
      const next: IInteraction | null = changes['interaction'].currentValue;
      const isSameConversation = !!(prev && next && prev._id === next._id);

      if (!changes['interaction'].firstChange) {
        this.clearAISuggestion();

        if (!isSameConversation) {
          // Switched to a different conversation — reset everything including pagination hints.
          this.replyForm.reset();
          this.resetReplyTextareaHeight();
          this.pendingAttachment = null;
          this.stopRecordingStream();
          this.replyToolbarExpanded = false;
          this.showEmojiPicker = false;
          this.optimisticReplies = [];
          this.visibleTimelineCount = this.timelinePageSize;
          this.hasOlderMessages = false;
          this.oldestMessageTimestamp = null;
          this.allIncomingMessages = [...((next as any)?.metadata?.incomingMessages || [])];
          this.syncOldestMessageCursorFromLoadedIncoming();
        } else if (next?.replies?.length) {
          // Same conversation refreshed — drop optimistic entries already confirmed server-side.
          this.optimisticReplies = this.optimisticReplies.filter(
            opt => !next.replies!.some(r => !r.isPlatformReply && this.serverReplySupersedesOptimistic(opt, r as any))
          );
        }
        this.updateTimeline();
      }

      // Scroll to the latest message only when conversation changes or new content arrived
      if (next) {
        if (!isSameConversation) {
          this.scheduleScrollToBottom('instant');
        } else {
          // Same conversation: only scroll if there is actually new content (replies or incoming messages)
          const prevReplies = prev?.replies?.length ?? 0;
          const nextReplies = next.replies?.length ?? 0;
          const prevIncoming = (prev as any)?.metadata?.incomingMessages?.length ?? 0;
          const nextIncoming = (next as any)?.metadata?.incomingMessages?.length ?? 0;
          const hasNewContent = nextReplies > prevReplies || nextIncoming > prevIncoming;
          if (hasNewContent) {
            this.scheduleScrollToBottom('smooth');
          }
        }
      }

      // Initialise allIncomingMessages on the very first change or same-conversation refresh
      if (changes['interaction'].firstChange || !isSameConversation) {
        this.allIncomingMessages = [...((next as any)?.metadata?.incomingMessages || [])];
        this.syncOldestMessageCursorFromLoadedIncoming();
      } else {
        // Same conversation refreshed — keep accumulated older messages, only merge latest page
        const latestPage: any[] = (next as any)?.metadata?.incomingMessages || [];
        // Use the mid as dedup key; fall back to index position
        const existingMids = new Set(this.allIncomingMessages.map((m: any) => m.mid).filter(Boolean));
        const newMsgs = latestPage.filter((m: any) => !m.mid || !existingMids.has(m.mid));
        if (newMsgs.length) {
          this.allIncomingMessages = [...this.allIncomingMessages, ...newMsgs];
        }
      }

      // Mark notifications as read when the conversation is viewed.
      // NOTE: marking the interaction itself as 'read' is handled exclusively
      // in onInteractionSelect() (the container), so we never override a
      // manually-set 'unread' status from a background lifecycle event.
      if (this.interaction && this.interaction._id) {
        this.markNotificationsAsRead();
      }

      // WhatsApp inbox: reload approved templates when conversation changes.
      if (changes['interaction'].firstChange || !isSameConversation) {
        this.resetWaTemplateState();
        this.loadWhatsAppTemplatesForInbox();
      }

      this.updateTimeline();
    }
  }

  /** Recompute and assign cached timeline (call when interaction or optimisticReplies change only) */
  private updateTimeline(): void {
    this.conversationTimeline = this.getConversationTimeline();
    this.updateVisibleTimeline();
  }

  ngOnDestroy(): void {
    this.timedTasks.unsubscribe();
    this.stopRecordingStream();
    this.subscriptions.forEach(sub => sub.unsubscribe());
  }

  @ViewChild('conversationThread') conversationThread?: ElementRef<HTMLDivElement>;

  constructor(
    private fb: FormBuilder,
    private inboxService: InboxService,
    public themeService: ThemeService,
    private userService: UserService,
    private authService: AuthService,
    private notificationDataService: NotificationDataService,
    private sweetAlertService: SweetAlertService,
    private cdr: ChangeDetectorRef,
    private ngZone: NgZone,
    private sanitizer: DomSanitizer,
    private avatarService: InboxAvatarService,
    private mediaLibraryService: MediaLibraryService,
    private whatsAppTemplateService: WhatsAppTemplateService,
    private catalogService: CatalogService,
    private notify: NotificationService
  ) {
    this.replyForm = this.fb.group({
      content: ['', [Validators.required, Validators.minLength(1)]]
    });
  }

  /** Toggle emoji picker panel */
  toggleEmojiPicker(): void {
    this.showEmojiPicker = !this.showEmojiPicker;
    this.cdr.markForCheck();
  }

  /** Expand/collapse the left reply tools plate (emoji, AI, attach, catalog). */
  toggleReplyToolbar(expanded?: boolean): void {
    this.replyToolbarExpanded = expanded ?? !this.replyToolbarExpanded;
    if (!this.replyToolbarExpanded) {
      this.showEmojiPicker = false;
    }
    this.cdr.markForCheck();
  }

  /** Insert emoji at cursor in reply textarea and update form */
  insertEmoji(emoji: string): void {
    const textarea = this.replyTextarea?.nativeElement;
    const control = this.replyForm.get('content');
    if (!textarea || !control) return;
    const start = textarea.selectionStart ?? 0;
    const end = textarea.selectionEnd ?? start;
    const current = control.value ?? '';
    const newValue = current.slice(0, start) + emoji + current.slice(end);
    control.setValue(newValue);
    control.markAsDirty();
    control.updateValueAndValidity();
    this.ngZone.runOutsideAngular(() => {
      this.timedTasks.add(
        timer(0)
          .pipe(take(1))
          .subscribe(() => {
            textarea.focus();
            textarea.setSelectionRange(start + emoji.length, start + emoji.length);
          })
      );
    });
    this.cdr.markForCheck();
  }

  /**
   * Get platform-specific colors for the interaction
   */
  onAvatarError(key: string): void {
    this.avatarFallback = { ...this.avatarFallback, [key]: true };
  }

  onWaPlatformBadgeError(platformId: string): void {
    if (!platformId) return;
    this.waPlatformBadgeError = { ...this.waPlatformBadgeError, [platformId]: true };
  }

  /** Observable avatar URL (fetched with auth for Facebook so img can display). */
  getAuthorAvatar$(author: IInteraction['author'], platform?: string, pageId?: string, threadPlatformId?: string): Observable<SafeUrl | null> {
    return this.avatarService.getAvatarUrl(platform ?? '', author, pageId, threadPlatformId).pipe(
      map(url => (url ? this.sanitizer.bypassSecurityTrustUrl(url) : null))
    );
  }

  /** Observable DM attachment image URL (Facebook: fetched via proxy with auth). */
  /** True when content is the placeholder we use for image-only messages (don't show under the image). */
  isImagePlaceholder(content: string | undefined): boolean {
    if (!content || typeof content !== 'string') return false;
    const t = content.trim();
    return /^(\[image\]|\[attachment\]|\[Image\])$/i.test(t);
  }

  /** Hide caption line for WhatsApp/media placeholder bodies (voice note, etc.). */
  isIncomingAttachmentCaptionHidden(content: string | undefined, attachmentType?: string): boolean {
    if (!content || typeof content !== 'string') return false;
    const t = content.trim();
    if (attachmentType === 'image' && this.isImagePlaceholder(content)) return true;
    if (attachmentType === 'video' && /^\[(video|Video)\]$/i.test(t)) return true;
    if (attachmentType === 'audio' && (/^\[audio\]$/i.test(t) || /^\[Audio Message\]$/i.test(t))) return true;
    if (attachmentType === 'file' && /^\[file\]$/i.test(t)) return true;
    return false;
  }

  /**
   * Return a SafeHtml value to use as [srcdoc] for email HTML rendering.
   * The iframe uses sandbox="allow-same-origin" to prevent script execution.
   */
  getSafeEmailHtml(html: string): SafeHtml {
    return this.sanitizer.bypassSecurityTrustHtml(html);
  }

  /**
   * Auto-resize iframe height after its content loads.
   */
  onEmailIframeLoad(event: Event): void {
    const iframe = event.target as HTMLIFrameElement;
    try {
      const body = iframe.contentDocument?.body;
      if (body) {
        iframe.style.height = Math.min(body.scrollHeight + 20, 600) + 'px';
      }
    } catch { /* cross-origin fallback — height remains at default */ }
  }

  /** Format an array of email address objects into a comma-separated display string. */
  formatEmailAddressList(addresses: Array<{ name?: string; address?: string }> | undefined): string {
    if (!addresses || addresses.length === 0) return '';
    return addresses
      .map(a => a.name ? `${a.name} <${a.address}>` : (a.address || ''))
      .filter(Boolean)
      .join(', ');
  }

  /** Format attachment file size for display. */
  formatAttachmentSize(bytes: number): string {
    if (!bytes || bytes === 0) return '';
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  }

  /** PDF / file attachment label (library name or last URL segment). */
  replyPdfFileLabel(reply: {
    attachmentUrl?: string;
    attachmentType?: string;
    attachmentDisplayName?: string;
  }): string {
    return inboxReplyPdfDisplayName(reply);
  }

  downloadInboxPdfReply(
    url: string | undefined,
    reply: { attachmentUrl?: string; attachmentType?: string; attachmentDisplayName?: string }
  ): void {
    if (!url) return;
    const name = inboxReplyPdfDisplayName({ ...reply, attachmentUrl: url });
    void downloadInboxAttachmentFile(url, name);
  }

  incomingFileAttachmentLabel(data: { attachmentUrl?: string }): string {
    return inboxAttachmentFilenameFromUrl(data.attachmentUrl);
  }

  getAttachmentUrl$(interactionId: string, mid: string, platform: string, directUrl: string | undefined): Observable<SafeUrl | null> {
    if ((platform === 'facebook' || platform === 'instagram') && interactionId && mid) {
      return this.avatarService.getAttachmentUrl(interactionId, mid).pipe(
        map(url => (url ? this.sanitizer.bypassSecurityTrustUrl(url) : null))
      );
    }
    if (platform === 'whatsapp' && interactionId && mid) {
      return this.avatarService.getWhatsAppAttachmentUrl(interactionId, mid).pipe(
        map(url => (url ? this.sanitizer.bypassSecurityTrustUrl(url) : null))
      );
    }
    return of(directUrl ? this.sanitizer.bypassSecurityTrustUrl(directUrl) : null);
  }

  /** Display name with platform fallback when profile isn't available (e.g. Instagram without Advanced Access). */
  getAuthorDisplayName(obj: { author?: IInteraction['author']; platform?: string } | null): string {
    if (!obj) return 'Unknown';
    const name = obj.author?.name || obj.author?.username;
    if (name) return name;
    if (obj.platform === 'instagram') return 'Instagram User';
    if (obj.platform === 'facebook') return 'Messenger User';
    return 'Unknown';
  }

  /** Support ticket / chat number shown in the header (#ORGCODE-101, or #101 if ref missing). */
  getTicketDisplay(interaction: IInteraction | null): string | null {
    if (!interaction) return null;
    const ref = interaction.chatRef?.trim();
    if (ref) return ref;
    if (interaction.chatNumber != null && !Number.isNaN(Number(interaction.chatNumber))) {
      return `#${interaction.chatNumber}`;
    }
    return null;
  }

  getConfidenceBadgeLabel(confidence: number | null): string {
    if (confidence == null) return 'Auto';
    if (confidence >= 0.85) return '✓ Auto';
    if (confidence >= 0.65) return '~ Auto';
    return '! Auto';
  }

  getConfidenceBadgeClass(confidence: number | null): string {
    if (confidence == null) return 'text-gray-500 dark:text-gray-400';
    if (confidence >= 0.85) return 'text-green-600 dark:text-green-400 bg-green-50 dark:bg-green-900/20';
    if (confidence >= 0.65) return 'text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-900/20';
    return 'text-red-500 dark:text-red-400 bg-red-50 dark:bg-red-900/20';
  }

  getPlatformColors(): any {
    if (!this.interaction) return null;
    const theme = this.themeService.getTheme(this.interaction.platform);
    return {
      primary: theme.primaryColor,
      secondary: theme.secondaryColor,
      gradientFrom: theme.gradientFrom,
      gradientTo: theme.gradientTo
    };
  }

  private loadWhatsAppTemplatesForInbox(): void {
    if (!this.interaction || this.interaction.platform !== Platform.WHATSAPP) {
      this.waApprovedTemplates = [];
      this.waTemplatesLoading = false;
      return;
    }
    const conn = this.interaction.platformConnection as { _id?: string } | undefined;
    const connId = conn?._id ? String(conn._id) : '';
    if (!connId) {
      this.waApprovedTemplates = [];
      return;
    }

    this.waTemplatesLoading = true;
    const sub = this.whatsAppTemplateService.listTemplates(connId).subscribe({
      next: (res) => {
        this.waApprovedTemplates = (res.templates || []).filter(
          (t) => String(t.status || '').toUpperCase() === 'APPROVED'
        );
        this.waTemplatesLoading = false;
        this.cdr.markForCheck();
      },
      error: () => {
        this.waApprovedTemplates = [];
        this.waTemplatesLoading = false;
        this.cdr.markForCheck();
      }
    });
    this.subscriptions.push(sub);
  }

  private resetWaTemplateState(): void {
    this.waReplyMode = 'text';
    this.waSelectedTemplate = null;
    this.waTemplateSlots = [];
    this.waTemplateParamValues = {};
  }

  setWaReplyMode(mode: 'text' | 'template'): void {
    this.waReplyMode = mode;
    if (mode === 'template') {
      if (this.isRecording || this.isUploadingRecording) {
        this.stopVoiceRecording();
      }
      this.pendingAttachment = null;
      this.replyForm.patchValue({ content: '' }, { emitEvent: false });
    } else {
      this.closeMediaSelector();
    }
    this.cdr.markForCheck();
  }

  onWaTemplatePick(nameOrEvent: string | Event): void {
    this.closeMediaSelector();
    const name =
      typeof nameOrEvent === 'string'
        ? nameOrEvent
        : ((nameOrEvent.target as HTMLSelectElement)?.value ?? '');
    const t =
      name && typeof name === 'string'
        ? this.waApprovedTemplates.find((x) => x.name === name) ?? null
        : null;

    this.waSelectedTemplate = t;
    this.waTemplateSlots = t ? listWhatsAppTemplateParamSlots(t) : [];
    this.waTemplateParamValues = {};
    this.waTemplateSlots.forEach((s) => {
      this.waTemplateParamValues[s.storageKey] = '';
    });
    this.cdr.markForCheck();
  }

  submitWhatsAppTemplateReply(): void {
    if (!this.interaction || this.submittingReply) return;
    const t = this.waSelectedTemplate;
    if (!t) {
      this.sweetAlertService.toast('warning', 'Choose an approved WhatsApp template.');
      return;
    }

    for (const slot of this.waTemplateSlots) {
      const v = (this.waTemplateParamValues[slot.storageKey] ?? '').trim();
      if (!v) {
        this.sweetAlertService.toast('warning', `Fill all fields (${slot.label}).`);
        return;
      }
      if (slot.paramKind === 'image' && !/^https:\/\//i.test(v)) {
        this.sweetAlertService.toast('warning', 'Header image must use a secure https:// URL.');
        return;
      }
    }

    const components = buildWhatsAppOutboundTemplateComponents(t, this.waTemplateSlots, this.waTemplateParamValues);
    const preview = buildWhatsAppTemplatePreviewDisplay(t, components);
    const waPayload = {
      name: t.name,
      languageCode: t.language,
      components,
      inboxUiPreview: preview
    };
    const displayContent =
      preview.bodyText?.trim() ||
      `\u00ab${t.name}\u00bb`;

    const optimistic: IOptimisticReply = {
      _optimistic: true,
      content: displayContent,
      sentAt: new Date(),
      sentBy: this.currentUser,
      status: 'pending',
      isPlatformReply: false,
      wasAutoGenerated: false,
      whatsappTemplatePayload: waPayload,
      whatsappTemplatePreview: preview
    };

    this.optimisticReplies = [...this.optimisticReplies, optimistic];
    this.updateTimeline();
    this.submittingReply = true;
    this.replySuccess = false;
    this.scheduleScrollToBottom('instant');

    this.inboxService
      .replyToInteraction(this.interaction._id, displayContent, undefined, undefined, undefined, undefined, waPayload)
      .subscribe({
        next: (response) => {
          this.submittingReply = false;
          if (response.success) {
            this.stripOptimisticDuplicatesFromApiReplies((response as any).data?.replies);
            this.replySuccess = true;
            this.interactionUpdate.emit();
            this.timedTasks.add(
              timer(3000)
                .pipe(take(1))
                .subscribe(() => {
                  this.replySuccess = false;
                })
            );
          } else {
            optimistic.status = 'failed';
            this.optimisticReplies = [...this.optimisticReplies];
            this.updateTimeline();
            const msg = (response as any).error || 'Template could not be sent.';
            this.sweetAlertService.toast('error', msg);
            this.cdr.markForCheck();
          }
        },
        error: (err) => {
          optimistic.status = 'failed';
          this.optimisticReplies = [...this.optimisticReplies];
          this.updateTimeline();
          this.submittingReply = false;
          const msg = err?.error?.error || err?.error?.message || err?.message || 'Could not send template.';
          this.sweetAlertService.toast('error', msg);
          this.cdr.markForCheck();
        }
      });
  }

  submitReply(): void {
    if (!this.interaction) return;

    if (this.interaction.platform === Platform.WHATSAPP && this.waReplyMode === 'template') {
      this.submitWhatsAppTemplateReply();
      return;
    }

    const content = (this.replyForm.value.content || '').trim();
    const hasAttachment = !!this.pendingAttachment;
    if (!content && !hasAttachment) return;

    const pendingWaMediaType = this.pendingAttachment?.mediaType;
    if (
      this.interaction.platform === Platform.WHATSAPP &&
      hasAttachment &&
      this.whatsappOutgoingMediaRequiresCaption(pendingWaMediaType) &&
      !content
    ) {
      this.sweetAlertService.toast(
        'error',
        'WhatsApp requires a message with images, videos, and files. Add text to your message, then send.'
      );
      return;
    }

    // Capture attachment before clearing (used for API and optimistic display)
    const attachmentUrl = this.pendingAttachment?.publicUrl;
    const attachmentType = this.pendingAttachment?.mediaType;
    const caption = content;
    const fileDisplayName =
      attachmentType === 'file' && attachmentUrl
        ? (this.pendingAttachment?.media?.originalName?.trim() ||
            this.pendingAttachment?.media?.filename?.trim() ||
            inboxAttachmentFilenameFromUrl(attachmentUrl))
        : undefined;

    // ── 1. Inject optimistic reply immediately ───────────────────────────────
    const displayContent = caption || (hasAttachment ? `[${attachmentType}]` : '');
    const optimistic: IOptimisticReply = {
      _optimistic: true,
      content: displayContent,
      sentAt: new Date(),
      sentBy: this.currentUser,
      status: 'pending',
      isPlatformReply: false,
      wasAutoGenerated: false,
      ...(attachmentUrl && attachmentType && {
        attachmentUrl,
        attachmentType,
        ...(fileDisplayName ? { attachmentDisplayName: fileDisplayName } : {})
      })
    };
    this.optimisticReplies = [...this.optimisticReplies, optimistic];
    this.updateTimeline();
    this.replyForm.reset();
    this.resetReplyTextareaHeight();
    this.pendingAttachment = null;
    this.submittingReply = true;
    this.replySuccess = false;
    this.scheduleScrollToBottom('instant');

    // ── 2. Send to backend (caption + optional attachment) ─────────────────
    this.inboxService.replyToInteraction(
      this.interaction._id,
      caption,
      undefined,
      undefined,
      attachmentUrl,
      attachmentType,
      undefined
    ).subscribe({
      next: (response) => {
        this.submittingReply = false;
        if (response.success) {
          this.stripOptimisticDuplicatesFromApiReplies((response as any).data?.replies);
          this.replySuccess = true;
          this.interactionUpdate.emit();
          this.timedTasks.add(
            timer(3000)
              .pipe(take(1))
              .subscribe(() => {
                this.replySuccess = false;
              })
          );
        } else {
          optimistic.status = 'failed';
          this.optimisticReplies = [...this.optimisticReplies];
          this.updateTimeline();
          const msg = (response as any).error || 'Reply could not be sent to the platform.';
          this.sweetAlertService.toast('error', msg);
          this.cdr.markForCheck();
        }
      },
      error: (err) => {
        optimistic.status = 'failed';
        this.optimisticReplies = [...this.optimisticReplies];
        this.updateTimeline();
        this.submittingReply = false;
        const msg = err?.error?.error || err?.error?.message || err?.message || 'Reply could not be sent. Check your connection and platform settings.';
        this.sweetAlertService.toast('error', msg);
        this.cdr.markForCheck();
      }
    });
  }

  onReplyTextareaKeydown(event: KeyboardEvent): void {
    // Enter sends message, Shift+Enter keeps newline behavior.
    if (event.key !== 'Enter' || event.shiftKey || event.isComposing) {
      return;
    }

    if (this.interaction?.platform === Platform.WHATSAPP && this.waReplyMode === 'template') {
      return;
    }

    event.preventDefault();

    if (this.submittingReply) return;
    const content = (this.replyForm.value.content || '').trim();
    const hasAttachment = !!this.pendingAttachment;
    if (!content && !hasAttachment) return;

    if (
      this.interaction?.platform === Platform.WHATSAPP &&
      hasAttachment &&
      this.whatsappOutgoingMediaRequiresCaption(this.pendingAttachment?.mediaType) &&
      !content
    ) {
      this.sweetAlertService.toast(
        'error',
        'WhatsApp requires a message with images, videos, and files. Add text to your message, then send.'
      );
      return;
    }

    this.submitReply();
  }

  openMediaSelector(): void {
    if (this.interaction?.platform === Platform.WHATSAPP && this.waReplyMode === 'template') {
      this.sweetAlertService.toast('info', 'Switch to “Free message” to attach media.');
      return;
    }
    this.mediaSelectorContext = 'reply';
    this.waTemplateImageSlotKey = null;
    this.showMediaModal = true;
  }

  openWaTemplateImagePicker(slot: WaParamSlot): void {
    this.mediaSelectorContext = 'waTemplateImage';
    this.waTemplateImageSlotKey = slot.storageKey;
    this.showMediaModal = true;
  }

  closeMediaSelector(): void {
    this.showMediaModal = false;
    this.mediaSelectorContext = null;
    this.waTemplateImageSlotKey = null;
  }

  /**
   * Platform limits for DM attachments (bytes).
   * Instagram: image 8MB, video/audio 25MB. Messenger: 25MB for all.
   */
  private getPlatformMediaLimits(): { imageMaxBytes: number; videoMaxBytes: number; audioMaxBytes: number } {
    const platform = this.interaction?.platform;
    if (platform === Platform.INSTAGRAM) {
      return { imageMaxBytes: 8 * 1024 * 1024, videoMaxBytes: 25 * 1024 * 1024, audioMaxBytes: 25 * 1024 * 1024 };
    }
    if (platform === Platform.FACEBOOK) {
      return { imageMaxBytes: 25 * 1024 * 1024, videoMaxBytes: 25 * 1024 * 1024, audioMaxBytes: 25 * 1024 * 1024 };
    }
    return { imageMaxBytes: 25 * 1024 * 1024, videoMaxBytes: 25 * 1024 * 1024, audioMaxBytes: 25 * 1024 * 1024 };
  }

  /** WhatsApp Cloud API: image, video, and document sends must include a user-visible caption (body). */
  private whatsappOutgoingMediaRequiresCaption(mediaType?: string | null): boolean {
    return !!mediaType && ['image', 'video', 'file'].includes(mediaType);
  }

  onMediaSelect(media: Media): void {
    if (this.mediaSelectorContext === 'waTemplateImage' && this.waTemplateImageSlotKey) {
      if (media.mediaType !== 'image') {
        this.sweetAlertService.toast('warning', 'Choose an image for the template header.');
        return;
      }
      this.waTemplateParamValues[this.waTemplateImageSlotKey] = media.publicUrl;
      this.closeMediaSelector();
      this.cdr.markForCheck();
      return;
    }

    if (!this.interaction) return;
    const limits = this.getPlatformMediaLimits();
    const size = media.size ?? 0;
    const isImage = media.mediaType === 'image';
    const isVideo = media.mediaType === 'video';
    const isAudio = media.mediaType === 'audio';
    const isFile = media.mediaType === 'file';
    const maxBytes = isImage
      ? limits.imageMaxBytes
      : isAudio
        ? limits.audioMaxBytes
        : isFile
          ? limits.videoMaxBytes
          : limits.videoMaxBytes;
    if (size > maxBytes) {
      const maxMB = Math.round(maxBytes / (1024 * 1024));
      this.sweetAlertService.toast('error', `This ${media.mediaType} is too large. Max ${maxMB}MB for this platform.`);
      return;
    }
    this.pendingAttachment = {
      publicUrl: media.publicUrl,
      mediaType: media.mediaType as 'image' | 'video' | 'audio' | 'file',
      media
    };
    this.closeMediaSelector();
    this.cdr.markForCheck();
  }

  removePendingAttachment(): void {
    this.pendingAttachment = null;
    this.cdr.markForCheck();
  }

  /** Start recording voice from microphone */
  async startVoiceRecording(): Promise<void> {
    if (!this.interaction || this.isRecording || this.isUploadingRecording) return;
    if (
      this.interaction.platform === Platform.WHATSAPP &&
      this.waReplyMode === 'template'
    ) {
      this.sweetAlertService.toast(
        'info',
        'Switch to “Free message” to record voice, or use Send template to customer.'
      );
      return;
    }
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      this.recordingStream = stream;
      this.recordedChunks = [];
      const mimeType = MediaRecorder.isTypeSupported('audio/webm;codecs=opus') ? 'audio/webm;codecs=opus' : 'audio/webm';
      const recorder = new MediaRecorder(stream);
      this.mediaRecorder = recorder;
      recorder.ondataavailable = (e: BlobEvent) => {
        if (e.data && e.data.size > 0) this.recordedChunks.push(e.data);
      };
      recorder.onstop = () => {
        this.timedTasks.add(
          timer(50)
            .pipe(take(1))
            .subscribe(() => this.finishVoiceRecording())
        );
      };
      recorder.start(100);
      this.isRecording = true;
      this.recordingDurationSec = 0;
      this.recordingTickSub?.unsubscribe();
      this.recordingTickSub = interval(1000).subscribe(() => {
        this.recordingDurationSec++;
        this.cdr.markForCheck();
      });
      this.cdr.markForCheck();
    } catch (err) {
      console.error('Voice recording start failed:', err);
      this.sweetAlertService.toast('error', 'Microphone access is needed to record. Please allow and try again.');
      this.stopRecordingStream();
      this.cdr.markForCheck();
    }
  }

  /** Stop recording and upload the audio */
  stopVoiceRecording(): void {
    if (!this.mediaRecorder || !this.isRecording) return;
    try {
      if (this.mediaRecorder.state === 'recording') {
        this.mediaRecorder.requestData();
      }
    } catch (_) {}
    this.mediaRecorder.stop();
    this.recordingTickSub?.unsubscribe();
    this.recordingTickSub = undefined;
    this.isRecording = false;
    this.cdr.markForCheck();
  }

  private finishVoiceRecording(): void {
    const chunks = [...this.recordedChunks];
    this.stopRecordingStream();
    if (!chunks.length) {
      this.sweetAlertService.toast('error', 'Recording too short. Try again.');
      this.cdr.markForCheck();
      return;
    }
    const blob = new Blob(chunks, { type: 'audio/webm' });
    const limits = this.getPlatformMediaLimits();
    if (blob.size > limits.audioMaxBytes) {
      const maxMB = Math.round(limits.audioMaxBytes / (1024 * 1024));
      this.sweetAlertService.toast('error', `Recording is too long. Max ${maxMB}MB for this platform.`);
      this.cdr.markForCheck();
      return;
    }
    const file = new File([blob], `voice-${Date.now()}.webm`, { type: 'audio/webm' });
    this.isUploadingRecording = true;
    this.cdr.markForCheck();
    this.mediaLibraryService.uploadMedia(file, [], 'Voice message').subscribe({
      next: (res) => {
        this.isUploadingRecording = false;
        if (res.success && res.data?.publicUrl) {
          this.pendingAttachment = {
            publicUrl: res.data.publicUrl,
            mediaType: 'audio',
            media: res.data
          };
          this.sweetAlertService.toast('success', 'Voice message ready. Add a caption (optional) and click Send.');
        } else {
          this.sweetAlertService.toast('error', 'Upload failed. Try again.');
        }
        this.cdr.markForCheck();
      },
      error: () => {
        this.isUploadingRecording = false;
        this.sweetAlertService.toast('error', 'Upload failed. Try again.');
        this.cdr.markForCheck();
      }
    });
  }

  private stopRecordingStream(): void {
    this.recordingTickSub?.unsubscribe();
    this.recordingTickSub = undefined;
    if (this.mediaRecorder && this.mediaRecorder.state !== 'inactive') {
      try { this.mediaRecorder.stop(); } catch {}
      this.mediaRecorder = null;
    }
    if (this.recordingStream) {
      this.recordingStream.getTracks().forEach(t => t.stop());
      this.recordingStream = null;
    }
    this.recordedChunks = [];
    this.isRecording = false;
    this.cdr.markForCheck();
  }

  /** Retry a failed optimistic reply */
  retryOptimisticReply(optimistic: IOptimisticReply): void {
    if (!this.interaction) return;
    optimistic.status = 'pending';
    this.optimisticReplies = [...this.optimisticReplies];
    this.updateTimeline();

    const wt = optimistic.whatsappTemplatePayload;
    const waMerged = wt
      ? {
          ...wt,
          ...(optimistic.whatsappTemplatePreview ? { inboxUiPreview: optimistic.whatsappTemplatePreview } : {})
        }
      : undefined;
    this.inboxService
      .replyToInteraction(
        this.interaction._id,
        optimistic.content,
        undefined,
        undefined,
        undefined,
        undefined,
        waMerged
      )
      .subscribe({
      next: (response) => {
        if (response.success) {
          this.optimisticReplies = this.optimisticReplies.filter(r => r !== optimistic);
          this.updateTimeline();
          this.interactionUpdate.emit();
        } else {
          optimistic.status = 'failed';
          this.optimisticReplies = [...this.optimisticReplies];
          this.updateTimeline();
          const msg = (response as any).error || 'Reply could not be sent to the platform.';
          this.sweetAlertService.toast('error', msg);
        }
        this.cdr.markForCheck();
      },
      error: (err) => {
        optimistic.status = 'failed';
        this.optimisticReplies = [...this.optimisticReplies];
        this.updateTimeline();
        const msg = err?.error?.error || err?.error?.message || err?.message || 'Reply could not be sent.';
        this.sweetAlertService.toast('error', msg);
        this.cdr.markForCheck();
      }
    });
  }

  /** Tracks scroll position to show/hide the FAB */
  onThreadScroll(event: Event): void {
    const el = event.target as HTMLDivElement;
    const distanceFromBottom = el.scrollHeight - el.scrollTop - el.clientHeight;
    this.isScrolledToBottom = distanceFromBottom < 80;

    if (el.scrollTop >= 80) return;

    this.syncOldestMessageCursorFromLoadedIncoming();

    // Prefer loading older *incoming DMs* from the API first. Previously we expanded the local
    // timeline (messages + replies + assignments) first; threads with few DMs but many replies or
    // history events exhausted many scroll-ups before hitting the API, which looked like
    // "pagination never triggers".
    if (this.hasOlderMessages && !this.loadingOlderFromServer && this.oldestMessageTimestamp != null) {
      this.loadOlderMessagesFromServer(el);
      return;
    }

    // Expand the visible window through locally cached timeline rows (same thread data).
    if (this.visibleTimelineCount < this.conversationTimeline.length) {
      this.loadingOlderMessages = true;
      const previousHeight = el.scrollHeight;
      this.visibleTimelineCount = Math.min(
        this.visibleTimelineCount + this.timelinePageSize,
        this.conversationTimeline.length
      );
      this.updateVisibleTimeline();
      this.ngZone.runOutsideAngular(() => {
        requestAnimationFrame(() => {
          const newHeight = el.scrollHeight;
          el.scrollTop += (newHeight - previousHeight);
          this.loadingOlderMessages = false;
          this.cdr.markForCheck();
        });
      });
    }
  }

  /** Fetch the page of messages that precede the oldest currently loaded message. */
  private loadOlderMessagesFromServer(scrollEl?: HTMLDivElement): void {
    this.syncOldestMessageCursorFromLoadedIncoming();
    if (!this.interaction?._id || this.oldestMessageTimestamp == null || this.loadingOlderFromServer) return;

    this.loadingOlderFromServer = true;
    this.cdr.markForCheck();

    this.inboxService.getInteraction(this.interaction._id, {
      sortOrder: this.timelineSortOrder,
      msgBefore: this.oldestMessageTimestamp,
      msgLimit: INBOX_THREAD_MESSAGE_PAGE_SIZE
    }).subscribe({
      next: (response: any) => {
        this.loadingOlderFromServer = false;
        if (response.success && response.data) {
          const olderPage: any[] = response.data?.metadata?.incomingMessages || [];
          if (olderPage.length > 0) {
            // Prepend older messages; deduplicate by mid
            const existingMids = new Set(this.allIncomingMessages.map((m: any) => m.mid).filter(Boolean));
            const newOlder = olderPage.filter((m: any) => !m.mid || !existingMids.has(m.mid));
            if (newOlder.length) {
              const previousHeight = scrollEl?.scrollHeight ?? 0;
              this.allIncomingMessages = [...newOlder, ...this.allIncomingMessages];
              // Extend visible count so the newly prepended items show up
              this.visibleTimelineCount += newOlder.length;
              this.updateTimeline();
              if (scrollEl) {
                this.ngZone.runOutsideAngular(() => {
                  requestAnimationFrame(() => {
                    scrollEl.scrollTop += (scrollEl.scrollHeight - previousHeight);
                    this.cdr.markForCheck();
                  });
                });
              }
            }
          }
          // Update pagination state for next scroll-up
          const pagination = response.pagination;
          this.hasOlderMessages = pagination?.hasOlderMessages ?? false;
          if (pagination?.oldestMessageTimestamp != null) {
            this.oldestMessageTimestamp = pagination.oldestMessageTimestamp as number;
          } else {
            this.syncOldestMessageCursorFromLoadedIncoming();
          }
        }
        this.cdr.markForCheck();
      },
      error: () => {
        this.loadingOlderFromServer = false;
        this.cdr.markForCheck();
      }
    });
  }

  toggleTimelineSort(): void {
    this.timelineSortOrder = this.timelineSortOrder === 'asc' ? 'desc' : 'asc';
    if (this.interaction?._id) {
      // Sorting source-of-truth from backend.
      this.inboxService.getInteraction(this.interaction._id, { sortOrder: this.timelineSortOrder }).subscribe({
        next: (response) => {
          if (response.success && response.data) {
            this.interaction = response.data;
            this.visibleTimelineCount = this.timelinePageSize;
            this.updateTimeline();
            this.scheduleScrollToBottom('instant');
          }
        },
        error: () => {
          // Fallback to current local timeline if backend call fails.
          this.updateTimeline();
        }
      });
      return;
    }
    this.updateTimeline();
  }

  private updateVisibleTimeline(): void {
    if (!this.conversationTimeline.length) {
      this.visibleConversationTimeline = [];
      return;
    }
    if (this.timelineSortOrder === 'asc') {
      // Show latest N while keeping chronological order.
      this.visibleConversationTimeline = this.conversationTimeline.slice(-this.visibleTimelineCount);
    } else {
      // Descending list starts with newest; expand downward.
      this.visibleConversationTimeline = this.conversationTimeline.slice(0, this.visibleTimelineCount);
    }
  }

  /**
   * Angular trackBy signature is `(index, item)` — before this fix the args were swapped,
   * which meant every CD cycle produced unstable keys and *ngFor rebuilt the entire
   * timeline on every audio tick / socket event / scroll-up. Now the key is genuinely
   * stable per message and *ngFor updates in place.
   */
  getTimelineMessageKey = (
    index: number,
    item: { type: 'message' | 'reply' | 'assignment' | 'note'; data: any; timestamp: Date }
  ): string => {
    const id = item?.data?._id || item?.data?.mid || `idx-${index}`;
    return `${item.type}-${id}-${new Date(item.timestamp).getTime()}`;
  };

  shouldShowLoadMore(content: string | undefined | null): boolean {
    return !!content && content.length > this.messagePreviewLimit;
  }

  isMessageExpanded(key: string): boolean {
    return this.expandedMessageKeys.has(key);
  }

  expandMessage(key: string): void {
    this.expandedMessageKeys.add(key);
  }

  getMessagePreview(content: string | undefined | null): string {
    if (!content) return '';
    if (content.length <= this.messagePreviewLimit) return content;
    return content.slice(0, this.messagePreviewLimit).trimEnd() + '...';
  }

  /**
   * Schedules a scroll to the bottom after Angular renders + browser paints.
   * Uses RxJS timer(0) → requestAnimationFrame so layout has settled.
   * 'instant' always scrolls (used when switching conversations).
   * 'smooth' only scrolls if the user is already near the bottom.
   */
  private scheduleScrollToBottom(behavior: 'smooth' | 'instant' = 'instant'): void {
    if (behavior === 'smooth' && !this.isScrolledToBottom) {
      // User has scrolled up to read history — don't interrupt them
      return;
    }
    // Run outside Angular zone to avoid triggering extra change-detection cycles
    this.ngZone.runOutsideAngular(() => {
      this.timedTasks.add(
        timer(0)
          .pipe(take(1))
          .subscribe(() => {
            requestAnimationFrame(() => {
              const el = this.conversationThread?.nativeElement;
              if (!el) return;
              if (behavior === 'smooth') {
                el.scrollTo({ top: el.scrollHeight, behavior: 'smooth' });
              } else {
                el.scrollTop = el.scrollHeight;
              }
              this.ngZone.run(() => {
                this.isScrolledToBottom = true;
              });
            });
          })
      );
    });
  }

  /** FAB button: scroll to latest message */
  scrollToBottom(): void {
    const el = this.conversationThread?.nativeElement;
    if (!el) return;
    el.scrollTo({ top: el.scrollHeight, behavior: 'smooth' });
    this.isScrolledToBottom = true;
  }

  getSentimentClass(sentiment?: string): string {
    switch (sentiment) {
      case 'positive':
        return 'bg-rep-lime/20 text-rep-black border border-rep-lime/30';
      case 'negative':
        return 'bg-gray-100 text-gray-800 border border-gray-300';
      default:
        return 'bg-gray-100 text-gray-800 border border-gray-300';
    }
  }

  formatDate(date: Date): string {
    return new Date(date).toLocaleString();
  }

  getStatusColor(status?: string): string {
    switch (status) {
      case 'unread':
        return 'bg-gray-100 text-gray-800 border border-gray-300';
      case 'replied':
        return 'bg-rep-lime/20 text-rep-black border border-rep-lime/30';
      case 'resolved':
        return 'bg-rep-lime/20 text-rep-black border border-rep-lime/30';
      default:
        return 'bg-gray-100 text-gray-800 border border-gray-300';
    }
  }

  getPlatformIcon(platform: string): string {
    const icons: { [key: string]: string } = {
      'instagram': '📷',
      'facebook': '📘',
      'whatsapp': '💬',
      'youtube': '📺',
      'google': '🔍'
    };
    return icons[platform.toLowerCase()] || '💬';
  }

  /** Font Awesome platform icon for header badge (matches inbox list). */
  getPlatformFaClass(platform: string | undefined | null): string {
    const p = (platform || '').toLowerCase().trim();
    const icons: Record<string, string> = {
      [Platform.INSTAGRAM]: 'fab fa-instagram',
      [Platform.FACEBOOK]: 'fab fa-facebook-f',
      [Platform.YOUTUBE]: 'fab fa-youtube',
      [Platform.GOOGLE]: 'fab fa-google',
      [Platform.LINKEDIN]: 'fab fa-linkedin-in',
      [Platform.WHATSAPP]: 'fab fa-whatsapp',
      [Platform.WEBSITE]: 'fas fa-globe',
      [Platform.EMAIL]: 'fas fa-envelope'
    };
    return icons[p] || 'fas fa-share-alt';
  }

  /** Star rating for reviews (Google Business etc.); undefined if not a review or no rating */
  getReviewRating(): number | undefined {
    if (!this.interaction) return undefined;
    const r = (this.interaction as any).rating ?? this.interaction.metadata?.starRating;
    if (r == null || typeof r !== 'number') return undefined;
    return Math.min(5, Math.max(1, Math.round(r)));
  }

  /** Detect numeric-ID Instagram URLs that are invalid web addresses. */
  private isNumericInstagramUrl(url: string): boolean {
    const m = url.match(/instagram\.com\/p\/([^/?#]+)/);
    if (!m) return false;
    return /^\d{14,}$/.test(m[1]);
  }

  /**
   * Returns post reference data for comment-type interactions.
   * Used by the detail view to render a "post card" linking back to the
   * original post/video that this comment belongs to.
   */
  getPostRef(): { title: string | null; url: string } | null {
    if (!this.interaction || this.interaction.type !== 'comment') return null;

    const m = (this.interaction as any).metadata as Record<string, unknown> | undefined;

    const pickStr = (v: unknown): string | null => {
      if (!v) return null;
      const s = String(v).trim();
      return s.length > 0 ? s : null;
    };

    const videoIdFromMeta = pickStr(m?.['videoId']);
    const platform = (this.interaction.platform || '').toLowerCase();

    const rawCandidates = [
      pickStr(m?.['postUrl']),
      videoIdFromMeta ? `https://www.youtube.com/watch?v=${videoIdFromMeta}` : null,
      pickStr((this.interaction as any).platformUrl),
    ];

    const url = rawCandidates.find(c => {
      if (!c) return false;
      if (platform === 'instagram' && this.isNumericInstagramUrl(c)) return false;
      return true;
    }) ?? null;

    if (!url) return null;

    const rawCaption = pickStr(m?.['mediaCaption']) || pickStr(m?.['postTitle']);
    const title =
      pickStr(m?.['videoTitle']) ||
      (rawCaption ? rawCaption.slice(0, 80) + (rawCaption.length > 80 ? '…' : '') : null);

    return { title: title || null, url };
  }

  /** Platform icon class for the post reference card */
  getPostRefIcon(): string {
    const map: Record<string, string> = {
      youtube: 'fa-brands fa-youtube',
      instagram: 'fa-brands fa-instagram',
      facebook: 'fa-brands fa-facebook',
      linkedin: 'fa-brands fa-linkedin',
      twitter: 'fa-brands fa-x-twitter',
      x: 'fa-brands fa-x-twitter',
    };
    const platform = (this.interaction?.platform || '').toLowerCase();
    return map[platform] || 'fas fa-link';
  }

  getSentimentIcon(sentiment?: string): string {
    switch (sentiment) {
      case 'positive':
        return '😊';
      case 'negative':
        return '😟';
      default:
        return '😐';
    }
  }

  getInitials(firstName?: string, lastName?: string): string {
    if (!firstName && !lastName) {
      return 'A';
    }
    const first = firstName?.charAt(0) || '';
    const last = lastName?.charAt(0) || '';
    return (first + last).toUpperCase() || 'A';
  }

  /** Returns up to 2 initials from a display name: "John Doe" → "JD", "John" → "JO". */
  getAuthorInitials(name: string): string {
    if (!name) return '?';
    const parts = name.trim().split(/\s+/);
    if (parts.length >= 2) {
      return ((parts[0][0] || '') + (parts[parts.length - 1][0] || '')).toUpperCase();
    }
    return name.substring(0, 2).toUpperCase();
  }

  /**
   * Check if sentBy is a populated user object or just a string ID
   */
  isUserObject(sentBy: string | any): boolean {
    return sentBy && typeof sentBy === 'object' && 'firstName' in sentBy;
  }

  /**
   * Get user's first name from sentBy (handles both string ID and populated object)
   */
  getUserFirstName(sentBy: string | any): string {
    if (this.isUserObject(sentBy)) {
      return (sentBy as any).firstName || '';
    }
    return '';
  }

  /**
   * Get user's last name from sentBy (handles both string ID and populated object)
   */
  getUserLastName(sentBy: string | any): string {
    if (this.isUserObject(sentBy)) {
      return (sentBy as any).lastName || '';
    }
    return '';
  }

  /**
   * Get user's full name from sentBy (handles both string ID and populated object)
   */
  getUserFullName(sentBy: string | any): string {
    if (this.isUserObject(sentBy)) {
      const firstName = (sentBy as any).firstName || '';
      const lastName = (sentBy as any).lastName || '';
      return `${firstName} ${lastName}`.trim() || 'Agent';
    }
    return 'Agent';
  }

  /**
   * Display name for outgoing replies: show the connected account/page (e.g. rep_me_up) for Facebook/Instagram
   * so the reply bubble shows the brand, not the logged-in user. Fallback to user name when no connection.
   */
  getReplySenderDisplayName(): string {
    const conn = (this.interaction as any)?.platformConnection;
    if (conn && (this.interaction?.platform === 'facebook' || this.interaction?.platform === 'instagram')) {
      return (conn.platformDisplayName || conn.platformUsername || '').trim() || 'RepMeUp';
    }
    return this.getUserFullName(this.currentUser);
  }

  /**
   * Avatar URL for outgoing replies: use the connected account/page profile picture when available.
   * Returns null if no image (template will show initials).
   */
  getReplySenderAvatarUrl(): SafeUrl | null {
    const conn = (this.interaction as any)?.platformConnection;
    const url = conn?.platformProfilePicture || conn?.metadata?.profilePicture;
    if (url && typeof url === 'string') {
      return this.sanitizer.bypassSecurityTrustUrl(url);
    }
    return null;
  }

  /**
   * Initials for reply sender: account name (e.g. "Rep Me Up" -> "RU") or user initials when no account.
   */
  getReplySenderInitials(): string {
    const conn = (this.interaction as any)?.platformConnection;
    if (conn && (this.interaction?.platform === 'facebook' || this.interaction?.platform === 'instagram')) {
      const name = (conn.platformDisplayName || conn.platformUsername || 'RepMeUp').trim();
      const parts = name.replace(/_/g, ' ').split(/\s+/).filter(Boolean);
      if (parts.length >= 2) {
        return (parts[0].charAt(0) + parts[parts.length - 1].charAt(0)).toUpperCase();
      }
      return name.charAt(0).toUpperCase() || 'R';
    }
    return this.getInitials(this.getUserFirstName(this.currentUser), this.getUserLastName(this.currentUser));
  }

  /**
   * Generate AI suggestion for reply
   */
  generateAISuggestion(): void {
    if (!this.interaction || this.generatingSuggestion) {
      return;
    }

    this.generatingSuggestion = true;
    this.suggestionError = null;
    this.aiSuggestion = null;

    this.inboxService.suggestReply(this.interaction._id).subscribe({
      next: (response) => {
        if (response.success && response.data) {
          this.aiSuggestion = {
            content: response.data.suggestedReply,
            confidence: response.data.confidence || 0,
            usedKnowledgeBase: response.data.usedKnowledgeBase || false
          };
          
          // Auto-fill the reply form with the suggestion
          this.replyForm.patchValue({
            content: this.aiSuggestion.content
          });

          // Show credit usage notification if credits are provided
          const credits = (response as any).credits;
          if (credits && credits.isNearLimit) {
            console.warn(`⚡ AI Credits Low: ${credits.remaining} remaining out of ${credits.limit}`);
          }
        } else {
          this.suggestionError = 'Failed to generate AI suggestion. Please try again.';
        }
        this.generatingSuggestion = false;
      },
      error: (error) => {
        console.error('Error generating AI suggestion:', error);
        
        // Handle specific credit-related errors
        if (error.error?.code === 'INSUFFICIENT_CREDITS' || error.error?.code === 'AI_CREDITS_EXCEEDED') {
          this.suggestionError = '⚡ You have run out of AI credits. Please upgrade your plan to continue using AI features.';
        } else {
          this.suggestionError = error.error?.error || error.error?.message || 'Failed to generate AI suggestion. Please try again.';
        }
        
        this.generatingSuggestion = false;
      }
    });
  }

  /**
   * Use the AI suggestion in the reply form
   */
  useAISuggestion(): void {
    if (this.aiSuggestion) {
      this.replyForm.patchValue({
        content: this.aiSuggestion.content
      });
    }
  }

  /**
   * Clear AI suggestion
   */
  clearAISuggestion(): void {
    this.aiSuggestion = null;
    this.suggestionError = null;
  }

  /**
   * Load available agents for assignment
   */
  loadAvailableAgents(): void {
    this.loadingAgents = true;
    this.userService.getAvailableAgents().subscribe({
      next: (response) => {
        if (response.success && response.data) {
          this.availableAgents = response.data;
        }
        this.loadingAgents = false;
      },
      error: (error) => {
        console.error('Error loading agents:', error);
        this.loadingAgents = false;
      }
    });
  }

  /**
   * Assign interaction to agent
   */
  assignToAgent(userId: string): void {
    if (!this.interaction || !this.interaction._id) {
      return;
    }

    // Don't assign if already assigned to this agent
    if (this.interaction.assignedTo && (this.interaction.assignedTo as any)._id === userId) {
      return;
    }

    this.assigningAgent = true;
    this.inboxService.assignInteraction(this.interaction._id, userId, 'manual').subscribe({
      next: (response) => {
        if (response.success) {
          // Refresh the interaction to get updated assignedTo data
          this.inboxService.getInteraction(this.interaction!._id, { sortOrder: this.timelineSortOrder }).subscribe({
            next: (refreshResponse) => {
              if (refreshResponse.success && refreshResponse.data) {
                this.interaction = refreshResponse.data;
                this.interactionUpdate.emit();
              }
              this.assigningAgent = false;
            }
          });
        }
      },
      error: (error) => {
        console.error('Error assigning interaction:', error);
        this.assigningAgent = false;
      }
    });
  }

  /**
   * Unassign interaction
   */
  unassignInteraction(): void {
    if (!this.interaction || !this.interaction._id || !this.interaction.assignedTo) {
      return;
    }

    this.sweetAlertService.confirm(
      'Unassign Interaction?',
      'Are you sure you want to unassign this interaction?',
      'Yes, Unassign',
      'Cancel'
    ).then((result) => {
      if (result.isConfirmed) {
        this.assigningAgent = true;
        this.sweetAlertService.showLoading('Unassigning...', 'Please wait');
        
        // Assign to empty string to unassign
        this.inboxService.assignInteraction(this.interaction!._id, '', 'manual').subscribe({
          next: (response) => {
            if (response.success) {
              // Refresh the interaction
              this.inboxService.getInteraction(this.interaction!._id, { sortOrder: this.timelineSortOrder }).subscribe({
                next: (refreshResponse) => {
                  this.sweetAlertService.close();
                  if (refreshResponse.success && refreshResponse.data) {
                    this.interaction = refreshResponse.data;
                    this.interactionUpdate.emit();
                    this.sweetAlertService.toast('success', 'Interaction unassigned successfully');
                  }
                  this.assigningAgent = false;
                },
                error: () => {
                  this.sweetAlertService.close();
                  this.assigningAgent = false;
                }
              });
            }
          },
          error: (error) => {
            this.sweetAlertService.close();
            this.sweetAlertService.error('Error', 'Failed to unassign interaction');
            console.error('Error unassigning interaction:', error);
            this.assigningAgent = false;
          }
        });
      }
    });
  }

  /**
   * Check if current user can assign interactions
   */
  canAssign(): boolean {
    return this.currentUser && (this.currentUser.role === 'admin' || this.currentUser.role === 'manager');
  }

  /**
   * Check if current user can reply to this interaction.
   * Agents can only reply when currently assigned; admin/manager can always reply.
   */
  canReply(): boolean {
    if (!this.currentUser || !this.interaction) return false;
    if (this.currentUser.role === 'admin' || this.currentUser.role === 'manager') return true;
    if (this.currentUser.role !== 'agent') return false;
    const assignedTo = this.interaction.assignedTo as any;
    return assignedTo && (assignedTo._id || assignedTo) === this.currentUser._id;
  }

  /**
   * Get assigned agent display name
   */
  getAssignedAgentName(): string {
    if (!this.interaction?.assignedTo) return '';
    const agent = this.interaction.assignedTo as any;
    if (agent.firstName && agent.lastName) {
      return `${agent.firstName} ${agent.lastName}`;
    }
    return agent.email || 'Unknown';
  }

  /**
   * Check if interaction is assigned
   */
  isAssigned(): boolean {
    return !!this.interaction?.assignedTo;
  }

  /**
   * Get assigned agent ID for dropdown value
   */
  getAssignedAgentId(): string {
    if (!this.interaction?.assignedTo) return '';
    const agent = this.interaction.assignedTo as any;
    return agent._id || '';
  }

  /**
   * Check if agent is currently assigned to this interaction
   */
  isAgentAssigned(agentId: string): boolean {
    if (!this.interaction?.assignedTo) return false;
    const agent = this.interaction.assignedTo as any;
    return agent._id === agentId;
  }

  /**
   * Resolve interaction
   */
  resolveInteraction(): void {
    if (!this.interaction || !this.interaction._id) {
      return;
    }

    this.sweetAlertService.confirm(
      'Mark as Resolved?',
      'Are you sure you want to mark this interaction as resolved? This will close the conversation.',
      'Yes, Resolve',
      'Cancel'
    ).then((result) => {
      if (result.isConfirmed) {
        this.resolvingInteraction = true;
        this.sweetAlertService.showLoading('Resolving...', 'Please wait');
        
        this.inboxService.updateStatus(this.interaction!._id, InteractionStatus.RESOLVED).subscribe({
          next: (response) => {
            if (response.success) {
              // Refresh the interaction
              this.inboxService.getInteraction(this.interaction!._id, { sortOrder: this.timelineSortOrder }).subscribe({
                next: (refreshResponse) => {
                  this.sweetAlertService.close();
                  if (refreshResponse.success && refreshResponse.data) {
                    this.interaction = refreshResponse.data;
                    this.interactionUpdate.emit();
                    this.sweetAlertService.success('Success!', 'Interaction marked as resolved');
                  }
                  this.resolvingInteraction = false;
                },
                error: () => {
                  this.sweetAlertService.close();
                  this.resolvingInteraction = false;
                }
              });
            }
          },
          error: (error) => {
            this.sweetAlertService.close();
            this.sweetAlertService.error('Error', 'Failed to resolve interaction');
            console.error('Error resolving interaction:', error);
            this.resolvingInteraction = false;
          }
        });
      }
    });
  }

  /**
   * Reopen interaction
   */
  reopenInteraction(): void {
    if (!this.interaction || !this.interaction._id) {
      return;
    }

    this.resolvingInteraction = true;
    this.inboxService.updateStatus(this.interaction._id, InteractionStatus.UNREAD).subscribe({
      next: (response) => {
        if (response.success) {
          // Refresh the interaction
          this.inboxService.getInteraction(this.interaction!._id, { sortOrder: this.timelineSortOrder }).subscribe({
            next: (refreshResponse) => {
              if (refreshResponse.success && refreshResponse.data) {
                this.interaction = refreshResponse.data;
                this.interactionUpdate.emit();
              }
              this.resolvingInteraction = false;
            }
          });
        }
      },
      error: (error) => {
        console.error('Error reopening interaction:', error);
        this.resolvingInteraction = false;
      }
    });
  }

  isChatSessionOpen(): boolean {
    return this.interaction != null && this.interaction.chatOpen !== false;
  }

  closeChatSession(): void {
    if (!this.interaction?._id) return;
    this.updatingChatOpen = true;
    this.inboxService.updateChatOpen(this.interaction._id, false).subscribe({
      next: (res) => {
        this.updatingChatOpen = false;
        if (res.success) {
          this.sweetAlertService.toast('success', 'Chat closed');
          this.interactionUpdate.emit();
        }
      },
      error: (err) => {
        this.updatingChatOpen = false;
        const msg = err?.error?.error || 'Could not close chat';
        this.sweetAlertService.toast('error', msg);
      }
    });
  }

  reopenChatSession(): void {
    if (!this.interaction?._id) return;
    this.updatingChatOpen = true;
    this.inboxService.updateChatOpen(this.interaction._id, true).subscribe({
      next: (res) => {
        this.updatingChatOpen = false;
        if (res.success) {
          this.sweetAlertService.toast('success', 'Chat opened');
          this.interactionUpdate.emit();
        }
      },
      error: (err) => {
        this.updatingChatOpen = false;
        const msg = err?.error?.error || 'Could not open chat';
        this.sweetAlertService.toast('error', msg);
      }
    });
  }

  /**
   * Check if interaction can be resolved
   */
  canResolve(): boolean {
    return this.interaction?.status !== InteractionStatus.RESOLVED;
  }

  /**
   * Check if interaction is resolved
   */
  isResolved(): boolean {
    return this.interaction?.status === InteractionStatus.RESOLVED;
  }

  /**
   * Whether this interaction is a Facebook comment that can be deleted (on Facebook and from inbox).
   */
  canDeleteComment(): boolean {
    return !!(this.interaction?.platform === 'facebook' && this.interaction?.type === 'comment');
  }

  /**
   * Whether to show the three-dots menu (Edit & Delete) — e.g. for Facebook comments.
   */
  showActionsMenuForInteraction(): boolean {
    return this.canDeleteComment();
  }

  toggleActionsMenu(event: Event): void {
    event.stopPropagation();
    this.showActionsMenu = !this.showActionsMenu;
  }

  closeActionsMenu(): void {
    this.showActionsMenu = false;
  }

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: MouseEvent): void {
    const target = (event?.target as HTMLElement) || null;
    if (this.showEmojiPicker && target && !target.closest('.inbox-emoji-picker-container')) {
      this.showEmojiPicker = false;
      this.cdr.markForCheck();
    }
    this.closeActionsMenu();
  }

  /**
   * Delete Facebook comment (on Facebook and from our DB), then close detail and refresh list.
   */
  deleteComment(): void {
    if (!this.interaction || !this.interaction._id || !this.canDeleteComment()) {
      return;
    }

    this.sweetAlertService.confirm(
      'Delete comment?',
      'This will remove the comment from Facebook and from your inbox. This cannot be undone.',
      'Yes, Delete',
      'Cancel'
    ).then((result) => {
      if (result.isConfirmed) {
        this.deletingComment = true;
        this.sweetAlertService.showLoading('Deleting...', 'Removing comment from Facebook and inbox');

        this.inboxService.deleteInteraction(this.interaction!._id).subscribe({
          next: (response) => {
            this.sweetAlertService.close();
            this.deletingComment = false;
            if (response.success) {
              this.inboxService.setSelectedInteraction(null);
              this.interactionUpdate.emit();
              this.sweetAlertService.toast('success', 'Comment deleted from Facebook and inbox.');
            } else {
              this.sweetAlertService.error('Error', (response as any).error || 'Failed to delete comment.');
            }
          },
          error: (err) => {
            this.sweetAlertService.close();
            this.deletingComment = false;
            const msg = err.error?.error || err.message || 'Failed to delete comment.';
            this.sweetAlertService.error('Error', msg);
          }
        });
      }
    });
  }

  deleteReplyMessage(reply: any): void {
    if (!this.interaction?._id || !reply?._id || this.deletingReplyId) return;
    if (reply.status !== 'failed') return;

    this.sweetAlertService.confirm(
      'Hide Failed Reply?',
      'This will hide only this failed (unsent) reply from conversation view. It will remain in the database.',
      'Yes, hide it',
      'Cancel'
    ).then((result) => {
      if (!result.isConfirmed) return;

      this.openReplyActionsForId = null;
      this.deletingReplyId = String(reply._id);
      this.inboxService.deleteReply(this.interaction!._id, String(reply._id)).subscribe({
        next: (response) => {
          this.deletingReplyId = null;
          if (response.success) {
            // Remove only this failed reply from local chat state (no full refresh).
            if (this.interaction?.replies) {
              this.interaction.replies = this.interaction.replies.filter(
                (r: any) => String(r?._id) !== String(reply._id)
              );
            }
            this.updateTimeline();
            this.cdr.markForCheck();
            this.sweetAlertService.toast('success', 'Reply hidden');
          } else {
            this.sweetAlertService.toast('error', (response as any).error || 'Failed to hide reply.');
          }
        },
        error: (err) => {
          this.deletingReplyId = null;
          const msg = err?.error?.error || err?.error?.message || 'Failed to hide reply.';
          this.sweetAlertService.toast('error', msg);
        }
      });
    });
  }

  toggleReplyActions(replyId: string): void {
    this.openReplyActionsForId = this.openReplyActionsForId === replyId ? null : replyId;
  }

  /**
   * Focus the reply textarea (used by keyboard shortcut R)
   */
  focusReplyBox(): void {
    this.timedTasks.add(
      timer(0)
        .pipe(take(1))
        .subscribe(() => this.replyTextarea?.nativeElement?.focus())
    );
  }

  insertReplyContent(content: string): void {
    this.replyForm.patchValue({ content });
    this.timedTasks.add(
      timer(0)
        .pipe(take(1))
        .subscribe(() => {
          const el = this.replyTextarea?.nativeElement;
          if (el) {
            el.focus();
            el.style.height = 'auto';
            el.style.height = el.scrollHeight + 'px';
          }
        })
    );
  }

  private resetReplyTextareaHeight(): void {
    const el = this.replyTextarea?.nativeElement;
    if (!el) return;
    el.style.height = '';
  }

  /**
   * Mark notifications related to this interaction as read
   */
  private markNotificationsAsRead(): void {
    if (!this.interaction || !this.interaction._id) return;

    // Get all notifications
    const notificationsSub = this.notificationDataService.notifications$.subscribe(notifications => {
      // Find unread notifications related to this interaction
      const relatedNotifications = notifications.filter(n => 
        !n.isRead && 
        n.relatedTo?.model === 'Interaction' && 
        n.relatedTo?.id === this.interaction!._id
      );

      // Mark each as read
      relatedNotifications.forEach(notification => {
        this.notificationDataService.markAsRead(notification._id).subscribe({
          error: (error) => {
            console.error('Error marking notification as read:', error);
          }
        });
      });
    });

    // Unsubscribe immediately after first emission
    this.subscriptions.push(notificationsSub);
    notificationsSub.unsubscribe();
  }

  /**
   * Get formatted assignment info for display.
   * When assignedBy is missing (e.g. auto-assign by system), show "System" instead of "Unknown user".
   */
  getAssignmentInfo(): { assignedToName: string; assignedByName: string; assignedAtFormatted: string } | null {
    if (!this.interaction?.assignedTo) {
      return null;
    }

    const assignedTo = this.interaction.assignedTo as any;
    const assignedBy = this.interaction.assignedBy as any;
    const assignedAt = this.interaction.assignedAt;

    const assignedToName = assignedTo.firstName && assignedTo.lastName
      ? `${assignedTo.firstName} ${assignedTo.lastName}`
      : assignedTo.name || 'Unknown Agent';
    const assignedByName = this.getAssignedByName(assignedBy);

    return {
      assignedToName,
      assignedByName,
      assignedAtFormatted: assignedAt ? this.formatAssignmentDate(new Date(assignedAt)) : ''
    };
  }

  /** Resolve "assigned by" label: user name or "System" when auto-assigned (no assignedBy). */
  private getAssignedByName(assignedBy: any): string {
    if (!assignedBy || (typeof assignedBy === 'object' && !assignedBy._id)) {
      return 'System';
    }
    if (assignedBy.firstName && assignedBy.lastName) {
      return `${assignedBy.firstName} ${assignedBy.lastName}`;
    }
    return assignedBy.name || 'System';
  }

  /**
   * Format assignment date like WhatsApp
   */
  private formatAssignmentDate(date: Date): string {
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    const diffMins = Math.floor(diff / 60000);
    const diffHours = Math.floor(diffMins / 60);
    const diffDays = Math.floor(diffHours / 24);

    const timeStr = date.toLocaleTimeString('en-US', { 
      hour: 'numeric', 
      minute: '2-digit', 
      hour12: true 
    });

    if (diffDays === 0) {
      return `Today at ${timeStr}`;
    } else if (diffDays === 1) {
      return `Yesterday at ${timeStr}`;
    } else if (diffDays < 7) {
      const dayName = date.toLocaleDateString('en-US', { weekday: 'long' });
      return `${dayName} at ${timeStr}`;
    } else {
      return date.toLocaleDateString('en-US', { 
        month: 'short', 
        day: 'numeric', 
        year: 'numeric',
        hour: 'numeric',
        minute: '2-digit',
        hour12: true
      });
    }
  }

  /**
   * Server may store `[WhatsApp Template] name (lang)` while optimistic uses rendered body text — then
   * `content === opt.content` never matches and both bubbles stayed on the timeline.
   */
  private static readonly WHATSAPP_TEMPLATE_DEDUP_MS = 5 * 60 * 1000;

  private static readonly ATTACHMENT_REPLY_DEDUP_MS = 2 * 60 * 1000;

  private serverReplySupersedesOptimistic(
    opt: Pick<IOptimisticReply, 'content' | 'sentAt' | 'whatsappTemplatePayload' | 'attachmentUrl' | 'attachmentType'>,
    serverReply: {
      content?: string;
      sentAt?: Date;
      isPlatformReply?: boolean;
      attachmentUrl?: string;
      attachmentType?: string;
      whatsappTemplatePreview?: { templateName?: string; languageCode?: string };
    }
  ): boolean {
    if (serverReply?.isPlatformReply) return false;
    const oc = (opt.content || '').trim();
    const sc = (serverReply.content || '').trim();
    if (oc && sc && oc === sc) return true;

    const optUrl = (opt as IOptimisticReply).attachmentUrl?.trim();
    const srvUrl = (serverReply as any).attachmentUrl?.trim();
    if (optUrl && srvUrl && optUrl === srvUrl) {
      return true;
    }

    const optAtt = (opt as IOptimisticReply).attachmentType;
    const srvAtt = serverReply.attachmentType;
    if (optAtt && srvAtt && optAtt === srvAtt) {
      const t0 = new Date(opt.sentAt).getTime();
      const t1 = new Date(serverReply.sentAt || 0).getTime();
      if (!Number.isNaN(t0) && !Number.isNaN(t1) && Math.abs(t1 - t0) <= InboxDetailComponent.ATTACHMENT_REPLY_DEDUP_MS) {
        const optPlaceholder = /^\[(image|video|audio|file)\]$/i.test(oc);
        const srvPlaceholderOrEmpty = !sc || /^\[(image|video|audio|file)\]$/i.test(sc);
        if (optPlaceholder && srvPlaceholderOrEmpty) {
          return true;
        }
        if (
          optAtt === 'audio' &&
          (optPlaceholder || oc === '🎤 Voice message') &&
          (!sc || srvPlaceholderOrEmpty || sc === '🎤 Voice message')
        ) {
          return true;
        }
      }
    }

    const wp = opt.whatsappTemplatePayload;
    if (!wp?.name) return false;

    const t0 = new Date(opt.sentAt).getTime();
    const t1 = new Date(serverReply.sentAt || 0).getTime();
    if (Number.isNaN(t0) || Number.isNaN(t1)) return false;
    if (Math.abs(t1 - t0) > InboxDetailComponent.WHATSAPP_TEMPLATE_DEDUP_MS) return false;

    const preview = serverReply.whatsappTemplatePreview;
    if (preview?.templateName === wp.name) {
      if (!wp.languageCode || !preview.languageCode) return true;
      if (preview.languageCode === wp.languageCode) return true;
      const baseLc = wp.languageCode.split(/[-_]/)[0]?.toLowerCase() || '';
      const basePr = preview.languageCode.split(/[-_]/)[0]?.toLowerCase() || '';
      return baseLc.length > 0 && baseLc === basePr;
    }

    const esc = wp.name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const bracketRe = new RegExp(`^\\[WhatsApp Template\\]\\s+${esc}\\s+\\(`, 'i');
    return bracketRe.test(sc);
  }

  /** Remove optimistic rows echoed in the latest POST /reply response (immediate — avoids duplicate bubbles). */
  private stripOptimisticDuplicatesFromApiReplies(replies: unknown): void {
    if (!Array.isArray(replies) || replies.length === 0) return;
    this.optimisticReplies = this.optimisticReplies.filter(
      opt => !replies.some((r: any) => !r.isPlatformReply && this.serverReplySupersedesOptimistic(opt, r))
    );
    this.updateTimeline();
  }

  /**
   * Get chronologically sorted timeline (messages, replies, assignments, notes)
   */
  getConversationTimeline(): Array<{type: 'message' | 'reply' | 'assignment' | 'note', data: any, timestamp: Date}> {
    if (!this.interaction) return [];

    const timeline: Array<{type: 'message' | 'reply' | 'assignment' | 'note', data: any, timestamp: Date}> = [];

    // Incoming messages: use the locally accumulated set (across all loaded server pages).
    // allIncomingMessages is seeded from the initial getInteraction response and extended
    // when the user scrolls up to load older pages from the server.
    const rawIncoming = this.allIncomingMessages.length
      ? this.allIncomingMessages
      : (this.interaction as any).metadata?.incomingMessages;
    // Deduplicate by mid so a retried webhook never shows the same message twice
    const seen = new Set<string>();
    const incoming = Array.isArray(rawIncoming)
      ? rawIncoming.filter((m: any) => {
          if (!m.mid || seen.has(m.mid)) return false;
          seen.add(m.mid);
          return true;
        })
      : rawIncoming;
    // Merge caption + media: when Meta sends caption and media (image/video) as two separate webhooks
    // (e.g. some Instagram / Messenger flows), show one bubble.
    //
    // WhatsApp Cloud API always includes image.caption / video.caption on the *same* message id, so we
    // store a single incomingMessages row. Consecutive rows are always separate user messages — do not
    // merge, or a text reply right after an image is wrongly shown as the image caption.
    const MEDIA_PLACEHOLDER_RE =
      /^\[(image|video|audio|file|Audio Message|Image|Video|Sticker)\]$/i;
    const isMediaPlaceholder = (t?: string) => !t || MEDIA_PLACEHOLDER_RE.test(String(t).trim());
    const mergedIncoming: Array<{ mid?: string; text?: string; timestamp?: number; attachmentUrl?: string; attachmentType?: string }> = [];
    const isWhatsApp = this.interaction?.platform === 'whatsapp';
    if (incoming && Array.isArray(incoming)) {
      for (let i = 0; i < incoming.length; i++) {
        const msg = incoming[i] as { mid?: string; text?: string; timestamp?: number; attachmentUrl?: string; attachmentType?: string };
        const next = incoming[i + 1] as { mid?: string; text?: string; timestamp?: number; attachmentUrl?: string; attachmentType?: string } | undefined;

        if (isWhatsApp) {
          mergedIncoming.push(msg);
          continue;
        }

        const nextIsImageOnly =
          next?.attachmentType === 'image' &&
          this.isImagePlaceholder(next?.text) &&
          (!!next?.attachmentUrl || !!next?.mid);
        const prevHasCaption =
          !!(msg.text && msg.text.trim()) && !msg.attachmentUrl && !msg.attachmentType;
        const msgIsImageOnly =
          msg.attachmentType === 'image' &&
          this.isImagePlaceholder(msg.text) &&
          (!!msg.attachmentUrl || !!msg.mid);
        const nextHasCaption =
          !!(next?.text && next.text.trim()) && !next?.attachmentUrl && !next?.attachmentType;
        const nextIsVideoOnly =
          next?.attachmentType === 'video' &&
          isMediaPlaceholder(next?.text) &&
          (!!next?.attachmentUrl || !!next?.mid);
        const msgIsVideoOnly =
          msg.attachmentType === 'video' &&
          isMediaPlaceholder(msg.text) &&
          (!!msg.attachmentUrl || !!msg.mid);
        if (nextIsImageOnly && prevHasCaption) {
          mergedIncoming.push({
            mid: next!.mid,
            text: msg.text,
            timestamp: next!.timestamp ?? msg.timestamp,
            attachmentUrl: next!.attachmentUrl,
            attachmentType: next!.attachmentType
          });
          i++;
        } else if (msgIsImageOnly && nextHasCaption) {
          mergedIncoming.push({
            mid: msg.mid,
            text: next!.text,
            timestamp: next!.timestamp ?? msg.timestamp,
            attachmentUrl: msg.attachmentUrl,
            attachmentType: msg.attachmentType
          });
          i++;
        } else if (nextIsVideoOnly && prevHasCaption) {
          mergedIncoming.push({
            mid: next!.mid,
            text: msg.text,
            timestamp: next!.timestamp ?? msg.timestamp,
            attachmentUrl: next!.attachmentUrl,
            attachmentType: next!.attachmentType
          });
          i++;
        } else if (msgIsVideoOnly && nextHasCaption) {
          mergedIncoming.push({
            mid: msg.mid,
            text: next!.text,
            timestamp: next!.timestamp ?? msg.timestamp,
            attachmentUrl: msg.attachmentUrl,
            attachmentType: msg.attachmentType
          });
          i++;
        } else {
          mergedIncoming.push(msg);
        }
      }
    }
    if (mergedIncoming.length > 0) {
      mergedIncoming.forEach((msg: { mid?: string; text?: string; timestamp?: number; attachmentUrl?: string; attachmentType?: string }) => {
        const ts = normalizeTimestampMs(msg.timestamp, new Date(this.interaction!.platformCreatedAt));
        timeline.push({
          type: 'message',
          data: {
            ...this.interaction,
            content: msg.text ?? (this.interaction as any).content,
            platformCreatedAt: ts,
            mid: msg.mid,
            attachmentUrl: msg.attachmentUrl,
            attachmentType: msg.attachmentType
          },
          timestamp: ts
        });
      });
    } else {
      timeline.push({
        type: 'message',
        data: this.interaction,
        timestamp: new Date(this.interaction.platformCreatedAt)
      });
    }

    // Add replies
    if (this.interaction.replies && this.interaction.replies.length > 0) {
      this.interaction.replies.forEach(reply => {
        timeline.push({
          type: 'reply',
          data: reply,
          timestamp: new Date(reply.sentAt)
        });
      });
    }

    // Add optimistic (pending / failed) replies that haven't been confirmed yet.
    const serverRs = this.interaction.replies || [];
    this.optimisticReplies.forEach(optimistic => {
      if (serverRs.some(r => !r.isPlatformReply && this.serverReplySupersedesOptimistic(optimistic, r as any))) {
        return;
      }
      timeline.push({
        type: 'reply',
        data: optimistic,
        timestamp: optimistic.sentAt
      });
    });

    // Add ALL assignment events from history
    if (this.interaction.assignmentHistory && this.interaction.assignmentHistory.length > 0) {
      this.interaction.assignmentHistory.forEach(assignment => {
        const assignedTo = assignment.assignedTo as any;
        const assignedBy = assignment.assignedBy as any;
        
        // Handle unassignment (assignedTo is null)
        if (!assignedTo) {
          timeline.push({
            type: 'assignment',
            data: {
              isUnassignment: true,
              assignedByName: this.getAssignedByName(assignedBy),
              assignedAtFormatted: this.formatAssignmentDate(new Date(assignment.assignedAt))
            },
            timestamp: new Date(assignment.assignedAt)
          });
        } else {
          // Regular assignment (use "System" when assignedBy is missing)
          timeline.push({
            type: 'assignment',
            data: {
              isUnassignment: false,
              assignedToName: assignedTo?.firstName && assignedTo?.lastName
                ? `${assignedTo.firstName} ${assignedTo.lastName}`
                : assignedTo?.name || 'Unknown Agent',
              assignedByName: this.getAssignedByName(assignedBy),
              assignedAtFormatted: this.formatAssignmentDate(new Date(assignment.assignedAt))
            },
            timestamp: new Date(assignment.assignedAt)
          });
        }
      });
    }

    // Add internal notes
    if (this.interaction.internalNotes && this.interaction.internalNotes.length > 0) {
      this.interaction.internalNotes.forEach((note: any) => {
        const addedBy = note.addedBy as any;
        const addedByName = addedBy?.firstName && addedBy?.lastName
          ? `${addedBy.firstName} ${addedBy.lastName}`
          : addedBy?.email || 'Unknown';
        timeline.push({
          type: 'note',
          data: {
            note: note.note,
            addedByName,
            addedAt: note.addedAt,
            isPrivate: note.isPrivate
          },
          timestamp: new Date(note.addedAt)
        });
      });
    }

    // Sort by timestamp based on selected order.
    const sorted = timeline.sort((a, b) => a.timestamp.getTime() - b.timestamp.getTime());
    return this.timelineSortOrder === 'asc' ? sorted : sorted.reverse();
  }

  // ── WhatsApp Product Picker ────────────────────────────────────────────────

  openProductPicker(preselect?: IProduct): void {
    this.showProductPickerModal = true;
    this.selectedPickerProduct = preselect || null;
    this.productPickerSearch = '';
    this.productPickerBodyText = '';
    this.productPickerError = '';
    this.loadPickerProducts();
    this.cdr.markForCheck();
  }

  /** Called by the AI assistant's "Send" chip for a suggested product */
  openProductPickerWithSuggestion(product: IProduct): void {
    this.openProductPicker(product);
  }

  closeProductPicker(): void {
    this.showProductPickerModal = false;
    this.selectedPickerProduct = null;
    this.productPickerError = '';
    this.cdr.markForCheck();
  }

  private loadPickerProducts(): void {
    this.loadingPickerProducts = true;
    this.cdr.markForCheck();
    this.catalogService.getProducts({ search: this.productPickerSearch || undefined, isActive: true, limit: 50 })
      .subscribe({
        next: r => {
          this.pickerProducts = r.data?.products ?? [];
          this.loadingPickerProducts = false;
          this.cdr.markForCheck();
        },
        error: () => {
          this.loadingPickerProducts = false;
          this.cdr.markForCheck();
        }
      });
  }

  onProductPickerSearch(): void {
    this.loadPickerProducts();
  }

  selectPickerProduct(product: IProduct): void {
    this.selectedPickerProduct = this.selectedPickerProduct?._id === product._id ? null : product;
    this.productPickerError = '';
    this.cdr.markForCheck();
  }

  sendProductFromPicker(): void {
    if (!this.selectedPickerProduct || !this.interaction || this.sendingProduct) return;
    this.sendingProduct = true;
    this.productPickerError = '';
    this.cdr.markForCheck();

    this.catalogService.sendWAProductMessage(
      this.interaction._id,
      this.selectedPickerProduct._id,
      this.productPickerBodyText.trim()
    ).subscribe({
      next: () => {
        this.sendingProduct = false;
        this.closeProductPicker();
        this.notify.success('Sent', `Product "${this.selectedPickerProduct?.name}" sent via WhatsApp.`);
        this.interactionUpdate.emit();
        this.cdr.markForCheck();
      },
      error: err => {
        this.sendingProduct = false;
        this.productPickerError = err.error?.error || 'Failed to send product message.';
        this.cdr.markForCheck();
      }
    });
  }

  trackByPickerProduct(_: number, p: IProduct): string { return p._id; }
}
